import type { Player } from "@/lib/types";
import { mkPlayer } from "./player-helpers";

// Effectifs à jour au 8 août 2026 (saison 2026 en cours) — vérifiés via
// recherche web (Wikipédia, pages de saison par équipe), meilleur effort à
// une date donnée : la ligue continue de bouger, donc de petits écarts sont
// possibles dès la prochaine fenêtre de transactions.
export const playersWnba: Player[] = [
  // --- Las Vegas Aces ---
  mkPlayer({ id: "aja-wilson", teamId: "las-vegas-aces", leagueId: "wnba", firstName: "A'ja", lastName: "Wilson", position: "C", jerseyNumber: 22, heightCm: 193, age: 30, overallRating: 98, injuryRisk: 15 }),
  mkPlayer({ id: "jewell-loyd", teamId: "las-vegas-aces", leagueId: "wnba", firstName: "Jewell", lastName: "Loyd", position: "SG", jerseyNumber: 24, heightCm: 180, age: 32, overallRating: 89 }),
  mkPlayer({ id: "chelsea-gray", teamId: "las-vegas-aces", leagueId: "wnba", firstName: "Chelsea", lastName: "Gray", position: "PG", jerseyNumber: 12, heightCm: 180, age: 33, overallRating: 83 }),
  mkPlayer({ id: "jackie-young", teamId: "las-vegas-aces", leagueId: "wnba", firstName: "Jackie", lastName: "Young", position: "SG", jerseyNumber: 0, heightCm: 183, age: 28, overallRating: 85 }),
  mkPlayer({ id: "nalyssa-smith", teamId: "las-vegas-aces", leagueId: "wnba", firstName: "NaLyssa", lastName: "Smith", position: "PF", jerseyNumber: 3, heightCm: 193, age: 26, overallRating: 78 }),
  mkPlayer({ id: "brianna-turner", teamId: "las-vegas-aces", leagueId: "wnba", firstName: "Brianna", lastName: "Turner", position: "PF", jerseyNumber: 21, heightCm: 191, age: 30, overallRating: 71 }),
  mkPlayer({ id: "cheyenne-parker-tyus", teamId: "las-vegas-aces", leagueId: "wnba", firstName: "Cheyenne", lastName: "Parker-Tyus", position: "PF", jerseyNumber: 32, heightCm: 193, age: 34, overallRating: 71 }),
  mkPlayer({ id: "dana-evans", teamId: "las-vegas-aces", leagueId: "wnba", firstName: "Dana", lastName: "Evans", position: "PG", jerseyNumber: 11, heightCm: 168, age: 28, overallRating: 70 }),
  mkPlayer({ id: "kierstan-bell", teamId: "las-vegas-aces", leagueId: "wnba", firstName: "Kierstan", lastName: "Bell", position: "SF", jerseyNumber: 1, heightCm: 185, age: 26, overallRating: 68 }),
  mkPlayer({ id: "stephanie-talbot", nationality: "Australie", teamId: "las-vegas-aces", leagueId: "wnba", firstName: "Stephanie", lastName: "Talbot", position: "SF", jerseyNumber: 7, heightCm: 188, age: 32, overallRating: 66 }),
  mkPlayer({ id: "justine-pissott", teamId: "las-vegas-aces", leagueId: "wnba", firstName: "Justine", lastName: "Pissott", position: "SF", jerseyNumber: 13, heightCm: 193, age: 22, overallRating: 60 }),
  mkPlayer({ id: "mai-yamamoto", nationality: "Japon", teamId: "las-vegas-aces", leagueId: "wnba", firstName: "Mai", lastName: "Yamamoto", position: "PG", jerseyNumber: 23, heightCm: 165, age: 26, overallRating: 62 }),

  // --- New York Liberty ---
  mkPlayer({ id: "breanna-stewart", teamId: "new-york-liberty", leagueId: "wnba", firstName: "Breanna", lastName: "Stewart", position: "PF", jerseyNumber: 30, heightCm: 193, age: 32, overallRating: 95, injuryRisk: 60 }),
  mkPlayer({ id: "sabrina-ionescu", teamId: "new-york-liberty", leagueId: "wnba", firstName: "Sabrina", lastName: "Ionescu", position: "PG", jerseyNumber: 20, heightCm: 180, age: 28, overallRating: 91, injuryRisk: 20 }),
  mkPlayer({ id: "jonquel-jones", teamId: "new-york-liberty", leagueId: "wnba", firstName: "Jonquel", lastName: "Jones", position: "C", jerseyNumber: 35, heightCm: 198, age: 32, overallRating: 86 }),
  mkPlayer({ id: "satou-sabally", nationality: "Allemagne", teamId: "new-york-liberty", leagueId: "wnba", firstName: "Satou", lastName: "Sabally", position: "PF", jerseyNumber: 0, heightCm: 193, age: 28, overallRating: 84 }),
  mkPlayer({ id: "leonie-fiebich", nationality: "Allemagne", teamId: "new-york-liberty", leagueId: "wnba", firstName: "Leonie", lastName: "Fiebich", position: "SF", jerseyNumber: 13, heightCm: 193, age: 26, overallRating: 78 }),
  mkPlayer({ id: "han-xu", nationality: "Chine", teamId: "new-york-liberty", leagueId: "wnba", firstName: "Han", lastName: "Xu", position: "C", jerseyNumber: 22, heightCm: 211, age: 26, overallRating: 68 }),
  mkPlayer({ id: "marine-johannes", nationality: "France", teamId: "new-york-liberty", leagueId: "wnba", firstName: "Marine", lastName: "Johannès", position: "PG", jerseyNumber: 23, heightCm: 178, age: 31, overallRating: 70 }),
  mkPlayer({ id: "rebecca-allen", teamId: "new-york-liberty", leagueId: "wnba", firstName: "Rebecca", lastName: "Allen", position: "SF", jerseyNumber: 9, heightCm: 188, age: 33, overallRating: 68 }),
  mkPlayer({ id: "marine-fauthoux", nationality: "France", teamId: "new-york-liberty", leagueId: "wnba", firstName: "Marine", lastName: "Fauthoux", position: "PG", jerseyNumber: 25, heightCm: 175, age: 25, overallRating: 66 }),
  mkPlayer({ id: "anneli-maley", nationality: "Australie", teamId: "new-york-liberty", leagueId: "wnba", firstName: "Anneli", lastName: "Maley", position: "SF", jerseyNumber: 34, heightCm: 185, age: 27, overallRating: 65 }),
  mkPlayer({ id: "pauline-astier", nationality: "France", teamId: "new-york-liberty", leagueId: "wnba", firstName: "Pauline", lastName: "Astier", position: "PG", jerseyNumber: 18, heightCm: 180, age: 24, overallRating: 63 }),
  mkPlayer({ id: "rebekah-gardner", teamId: "new-york-liberty", leagueId: "wnba", firstName: "Rebekah", lastName: "Gardner", position: "SF", jerseyNumber: 7, heightCm: 185, age: 36, overallRating: 62 }),

  // --- Seattle Storm ---
  mkPlayer({ id: "ezi-magbegor", nationality: "Australie", teamId: "seattle-storm", leagueId: "wnba", firstName: "Ezi", lastName: "Magbegor", position: "C", jerseyNumber: 13, heightCm: 193, age: 27, overallRating: 78, injuryRisk: 45 }),
  mkPlayer({ id: "dominique-malonga", nationality: "France", teamId: "seattle-storm", leagueId: "wnba", firstName: "Dominique", lastName: "Malonga", position: "C", jerseyNumber: 21, heightCm: 198, age: 20, overallRating: 74 }),
  mkPlayer({ id: "katie-lou-samuelson", teamId: "seattle-storm", leagueId: "wnba", firstName: "Katie Lou", lastName: "Samuelson", position: "SF", jerseyNumber: 33, heightCm: 191, age: 29, overallRating: 71 }),
  mkPlayer({ id: "jordan-horston", teamId: "seattle-storm", leagueId: "wnba", firstName: "Jordan", lastName: "Horston", position: "SF", jerseyNumber: 23, heightCm: 188, age: 25, overallRating: 73 }),
  mkPlayer({ id: "flaujae-johnson", teamId: "seattle-storm", leagueId: "wnba", firstName: "Flau'jae", lastName: "Johnson", position: "SF", jerseyNumber: 4, heightCm: 178, age: 22, overallRating: 71 }),
  mkPlayer({ id: "mackenzie-holmes", teamId: "seattle-storm", leagueId: "wnba", firstName: "Mackenzie", lastName: "Holmes", position: "PF", jerseyNumber: 44, heightCm: 191, age: 25, overallRating: 70 }),
  mkPlayer({ id: "zia-cooke", teamId: "seattle-storm", leagueId: "wnba", firstName: "Zia", lastName: "Cooke", position: "PG", jerseyNumber: 1, heightCm: 175, age: 25, overallRating: 68 }),
  mkPlayer({ id: "natisha-hiedeman", teamId: "seattle-storm", leagueId: "wnba", firstName: "Natisha", lastName: "Hiedeman", position: "PG", jerseyNumber: 2, heightCm: 173, age: 30, overallRating: 68 }),
  mkPlayer({ id: "stefanie-dolson", teamId: "seattle-storm", leagueId: "wnba", firstName: "Stefanie", lastName: "Dolson", position: "C", jerseyNumber: 31, heightCm: 196, age: 34, overallRating: 67 }),
  mkPlayer({ id: "jade-melbourne", nationality: "Australie", teamId: "seattle-storm", leagueId: "wnba", firstName: "Jade", lastName: "Melbourne", position: "PG", jerseyNumber: 8, heightCm: 178, age: 24, overallRating: 68 }),
  mkPlayer({ id: "awa-fam", nationality: "Espagne", teamId: "seattle-storm", leagueId: "wnba", firstName: "Awa", lastName: "Fam", position: "C", jerseyNumber: 11, heightCm: 193, age: 20, overallRating: 64 }),
  mkPlayer({ id: "taina-mair", teamId: "seattle-storm", leagueId: "wnba", firstName: "Taina", lastName: "Mair", position: "PG", jerseyNumber: 22, heightCm: 175, age: 22, overallRating: 48 }),

  // --- Connecticut Sun ---
  mkPlayer({ id: "brittney-griner", teamId: "connecticut-sun", leagueId: "wnba", firstName: "Brittney", lastName: "Griner", position: "C", jerseyNumber: 42, heightCm: 206, age: 35, overallRating: 79, injuryRisk: 35 }),
  mkPlayer({ id: "diamond-miller", teamId: "connecticut-sun", leagueId: "wnba", firstName: "Diamond", lastName: "Miller", position: "SF", jerseyNumber: 1, heightCm: 185, age: 26, overallRating: 74 }),
  mkPlayer({ id: "hailey-van-lith", teamId: "connecticut-sun", leagueId: "wnba", firstName: "Hailey", lastName: "Van Lith", position: "PG", jerseyNumber: 2, heightCm: 175, age: 24, overallRating: 73 }),
  mkPlayer({ id: "aaliyah-edwards", teamId: "connecticut-sun", leagueId: "wnba", firstName: "Aaliyah", lastName: "Edwards", position: "PF", jerseyNumber: 8, heightCm: 190, age: 23, overallRating: 75 }),
  mkPlayer({ id: "olivia-nelson-ododa", teamId: "connecticut-sun", leagueId: "wnba", firstName: "Olivia", lastName: "Nelson-Ododa", position: "C", jerseyNumber: 10, heightCm: 196, age: 26, overallRating: 67 }),
  mkPlayer({ id: "raegan-beers", teamId: "connecticut-sun", leagueId: "wnba", firstName: "Raegan", lastName: "Beers", position: "PF", jerseyNumber: 15, heightCm: 193, age: 22, overallRating: 68 }),
  mkPlayer({ id: "kennedy-burke", teamId: "connecticut-sun", leagueId: "wnba", firstName: "Kennedy", lastName: "Burke", position: "SG", jerseyNumber: 25, heightCm: 185, age: 29, overallRating: 68 }),
  mkPlayer({ id: "rayah-marshall", teamId: "connecticut-sun", leagueId: "wnba", firstName: "Rayah", lastName: "Marshall", position: "C", jerseyNumber: 13, heightCm: 193, age: 23, overallRating: 65 }),
  mkPlayer({ id: "saniya-rivers", teamId: "connecticut-sun", leagueId: "wnba", firstName: "Saniya", lastName: "Rivers", position: "SG", jerseyNumber: 22, heightCm: 185, age: 23, overallRating: 65 }),
  mkPlayer({ id: "ashlon-jackson", teamId: "connecticut-sun", leagueId: "wnba", firstName: "Ashlon", lastName: "Jackson", position: "PG", jerseyNumber: 3, heightCm: 183, age: 22, overallRating: 64 }),
  mkPlayer({ id: "gianna-kneepkens", teamId: "connecticut-sun", leagueId: "wnba", firstName: "Gianna", lastName: "Kneepkens", position: "SG", jerseyNumber: 5, heightCm: 180, age: 23, overallRating: 62 }),
  mkPlayer({ id: "nell-angloma", nationality: "France", teamId: "connecticut-sun", leagueId: "wnba", firstName: "Nell", lastName: "Angloma", position: "SF", jerseyNumber: 33, heightCm: 185, age: 20, overallRating: 66 }),

  // --- Minnesota Lynx ---
  mkPlayer({ id: "napheesa-collier", teamId: "minnesota-lynx", leagueId: "wnba", firstName: "Napheesa", lastName: "Collier", position: "PF", jerseyNumber: 24, heightCm: 185, age: 29, overallRating: 96, injuryRisk: 18 }),
  mkPlayer({ id: "kayla-mcbride", teamId: "minnesota-lynx", leagueId: "wnba", firstName: "Kayla", lastName: "McBride", position: "SG", jerseyNumber: 21, heightCm: 180, age: 34, overallRating: 83 }),
  mkPlayer({ id: "courtney-williams", teamId: "minnesota-lynx", leagueId: "wnba", firstName: "Courtney", lastName: "Williams", position: "PG", jerseyNumber: 10, heightCm: 173, age: 32, overallRating: 82 }),
  mkPlayer({ id: "olivia-miles", teamId: "minnesota-lynx", leagueId: "wnba", firstName: "Olivia", lastName: "Miles", position: "PG", jerseyNumber: 5, heightCm: 178, age: 23, overallRating: 76 }),
  mkPlayer({ id: "dorka-juhasz", nationality: "Hongrie", teamId: "minnesota-lynx", leagueId: "wnba", firstName: "Dorka", lastName: "Juhász", position: "C", jerseyNumber: 14, heightCm: 196, age: 26, overallRating: 74 }),
  mkPlayer({ id: "natasha-howard", teamId: "minnesota-lynx", leagueId: "wnba", firstName: "Natasha", lastName: "Howard", position: "PF", jerseyNumber: 33, heightCm: 191, age: 34, overallRating: 76 }),
  mkPlayer({ id: "nia-coffey", teamId: "minnesota-lynx", leagueId: "wnba", firstName: "Nia", lastName: "Coffey", position: "PF", jerseyNumber: 12, heightCm: 185, age: 30, overallRating: 68 }),
  mkPlayer({ id: "chloe-bibby", nationality: "Australie", teamId: "minnesota-lynx", leagueId: "wnba", firstName: "Chloe", lastName: "Bibby", position: "SF", jerseyNumber: 1, heightCm: 188, age: 27, overallRating: 66 }),
  mkPlayer({ id: "maya-caldwell", teamId: "minnesota-lynx", leagueId: "wnba", firstName: "Maya", lastName: "Caldwell", position: "SG", jerseyNumber: 2, heightCm: 180, age: 25, overallRating: 66 }),
  mkPlayer({ id: "liatu-king", teamId: "minnesota-lynx", leagueId: "wnba", firstName: "Liatu", lastName: "King", position: "PF", jerseyNumber: 11, heightCm: 180, age: 24, overallRating: 64 }),
  mkPlayer({ id: "antonia-delaere", nationality: "Belgique", teamId: "minnesota-lynx", leagueId: "wnba", firstName: "Antonia", lastName: "Delaere", position: "SF", jerseyNumber: 8, heightCm: 180, age: 32, overallRating: 58 }),
  mkPlayer({ id: "anastasiia-kosu", nationality: "Russie", teamId: "minnesota-lynx", leagueId: "wnba", firstName: "Anastasiia", lastName: "Kosu", position: "SF", jerseyNumber: 7, heightCm: 185, age: 21, overallRating: 52 }),

  // --- Indiana Fever ---
  mkPlayer({ id: "caitlin-clark", teamId: "indiana-fever", leagueId: "wnba", firstName: "Caitlin", lastName: "Clark", position: "PG", jerseyNumber: 22, heightCm: 183, age: 24, overallRating: 90, injuryRisk: 35 }),
  mkPlayer({ id: "aliyah-boston", teamId: "indiana-fever", leagueId: "wnba", firstName: "Aliyah", lastName: "Boston", position: "C", jerseyNumber: 7, heightCm: 196, age: 24, overallRating: 87 }),
  mkPlayer({ id: "kelsey-mitchell", teamId: "indiana-fever", leagueId: "wnba", firstName: "Kelsey", lastName: "Mitchell", position: "SG", jerseyNumber: 0, heightCm: 173, age: 31, overallRating: 82 }),
  mkPlayer({ id: "sophie-cunningham", teamId: "indiana-fever", leagueId: "wnba", firstName: "Sophie", lastName: "Cunningham", position: "SG", jerseyNumber: 8, heightCm: 185, age: 30, overallRating: 71 }),
  mkPlayer({ id: "damiris-dantas", nationality: "Brésil", teamId: "indiana-fever", leagueId: "wnba", firstName: "Damiris", lastName: "Dantas", position: "PF", jerseyNumber: 21, heightCm: 193, age: 33, overallRating: 67 }),
  mkPlayer({ id: "lexie-hull", teamId: "indiana-fever", leagueId: "wnba", firstName: "Lexie", lastName: "Hull", position: "SG", jerseyNumber: 10, heightCm: 188, age: 26, overallRating: 73 }),
  mkPlayer({ id: "myisha-hines-allen", teamId: "indiana-fever", leagueId: "wnba", firstName: "Myisha", lastName: "Hines-Allen", position: "PF", jerseyNumber: 2, heightCm: 188, age: 29, overallRating: 74 }),
  mkPlayer({ id: "tyasha-harris", teamId: "indiana-fever", leagueId: "wnba", firstName: "Tyasha", lastName: "Harris", position: "PG", jerseyNumber: 52, heightCm: 178, age: 28, overallRating: 71 }),
  mkPlayer({ id: "makayla-timpson", teamId: "indiana-fever", leagueId: "wnba", firstName: "Makayla", lastName: "Timpson", position: "PF", jerseyNumber: 43, heightCm: 188, age: 24, overallRating: 65 }),
  mkPlayer({ id: "raven-johnson", teamId: "indiana-fever", leagueId: "wnba", firstName: "Raven", lastName: "Johnson", position: "PG", jerseyNumber: 25, heightCm: 173, age: 23, overallRating: 64 }),
  mkPlayer({ id: "monique-billings", teamId: "indiana-fever", leagueId: "wnba", firstName: "Monique", lastName: "Billings", position: "PF", jerseyNumber: 25, heightCm: 193, age: 30, overallRating: 68 }),
  mkPlayer({ id: "grace-vanslooten", teamId: "indiana-fever", leagueId: "wnba", firstName: "Grace", lastName: "VanSlooten", position: "PF", jerseyNumber: 14, heightCm: 191, age: 22, overallRating: 60 }),

  // --- Atlanta Dream ---
  mkPlayer({ id: "rhyne-howard", teamId: "atlanta-dream", leagueId: "wnba", firstName: "Rhyne", lastName: "Howard", position: "SG", jerseyNumber: 10, heightCm: 188, age: 26, overallRating: 84 }),
  mkPlayer({ id: "allisha-gray", teamId: "atlanta-dream", leagueId: "wnba", firstName: "Allisha", lastName: "Gray", position: "SG", jerseyNumber: 15, heightCm: 183, age: 31, overallRating: 85 }),
  mkPlayer({ id: "brionna-jones", teamId: "atlanta-dream", leagueId: "wnba", firstName: "Brionna", lastName: "Jones", position: "C", jerseyNumber: 42, heightCm: 191, age: 30, overallRating: 78 }),
  mkPlayer({ id: "angel-reese", teamId: "atlanta-dream", leagueId: "wnba", firstName: "Angel", lastName: "Reese", position: "PF", jerseyNumber: 5, heightCm: 193, age: 24, overallRating: 84 }),
  mkPlayer({ id: "jordin-canada", teamId: "atlanta-dream", leagueId: "wnba", firstName: "Jordin", lastName: "Canada", position: "PG", jerseyNumber: 21, heightCm: 168, age: 30, overallRating: 77 }),
  mkPlayer({ id: "naz-hillmon", teamId: "atlanta-dream", leagueId: "wnba", firstName: "Naz", lastName: "Hillmon", position: "PF", jerseyNumber: 5, heightCm: 188, age: 26, overallRating: 74 }),
  mkPlayer({ id: "te-hina-paopao", teamId: "atlanta-dream", leagueId: "wnba", firstName: "Te-Hina", lastName: "Paopao", position: "PG", jerseyNumber: 12, heightCm: 175, age: 23, overallRating: 71 }),
  mkPlayer({ id: "sika-kone", nationality: "Mali", teamId: "atlanta-dream", leagueId: "wnba", firstName: "Sika", lastName: "Koné", position: "PF", jerseyNumber: 20, heightCm: 191, age: 24, overallRating: 67 }),
  mkPlayer({ id: "shatori-walker-kimbrough", teamId: "atlanta-dream", leagueId: "wnba", firstName: "Shatori", lastName: "Walker-Kimbrough", position: "SG", jerseyNumber: 1, heightCm: 175, age: 31, overallRating: 65 }),
  mkPlayer({ id: "jaylyn-sherrod", teamId: "atlanta-dream", leagueId: "wnba", firstName: "Jaylyn", lastName: "Sherrod", position: "PG", jerseyNumber: 4, heightCm: 170, age: 25, overallRating: 64 }),
  mkPlayer({ id: "madina-okot", nationality: "Kenya", teamId: "atlanta-dream", leagueId: "wnba", firstName: "Madina", lastName: "Okot", position: "C", jerseyNumber: 11, heightCm: 198, age: 21, overallRating: 63 }),
  mkPlayer({ id: "aaliyah-nye", teamId: "atlanta-dream", leagueId: "wnba", firstName: "Aaliyah", lastName: "Nye", position: "SG", jerseyNumber: 32, heightCm: 183, age: 23, overallRating: 62 }),

  // --- Chicago Sky ---
  mkPlayer({ id: "kamilla-cardoso", nationality: "Brésil", teamId: "chicago-sky", leagueId: "wnba", firstName: "Kamilla", lastName: "Cardoso", position: "C", jerseyNumber: 10, heightCm: 201, age: 25, overallRating: 79 }),
  mkPlayer({ id: "dijonai-carrington", teamId: "chicago-sky", leagueId: "wnba", firstName: "DiJonai", lastName: "Carrington", position: "SG", jerseyNumber: 7, heightCm: 180, age: 28, overallRating: 79 }),
  mkPlayer({ id: "rickea-jackson", teamId: "chicago-sky", leagueId: "wnba", firstName: "Rickea", lastName: "Jackson", position: "SF", jerseyNumber: 2, heightCm: 188, age: 24, overallRating: 77 }),
  mkPlayer({ id: "azura-stevens", teamId: "chicago-sky", leagueId: "wnba", firstName: "Azurá", lastName: "Stevens", position: "PF", jerseyNumber: 23, heightCm: 198, age: 30, overallRating: 76 }),
  mkPlayer({ id: "courtney-vandersloot", teamId: "chicago-sky", leagueId: "wnba", firstName: "Courtney", lastName: "Vandersloot", position: "PG", jerseyNumber: 22, heightCm: 173, age: 37, overallRating: 73 }),
  mkPlayer({ id: "skylar-diggins", teamId: "chicago-sky", leagueId: "wnba", firstName: "Skylar", lastName: "Diggins", position: "PG", jerseyNumber: 4, heightCm: 175, age: 36, overallRating: 78 }),
  mkPlayer({ id: "elizabeth-williams", teamId: "chicago-sky", leagueId: "wnba", firstName: "Elizabeth", lastName: "Williams", position: "C", jerseyNumber: 1, heightCm: 191, age: 33, overallRating: 69 }),
  mkPlayer({ id: "natasha-cloud", teamId: "chicago-sky", leagueId: "wnba", firstName: "Natasha", lastName: "Cloud", position: "PG", jerseyNumber: 9, heightCm: 180, age: 34, overallRating: 73 }),
  mkPlayer({ id: "maddy-westbeld", teamId: "chicago-sky", leagueId: "wnba", firstName: "Maddy", lastName: "Westbeld", position: "PF", jerseyNumber: 21, heightCm: 191, age: 24, overallRating: 69 }),
  mkPlayer({ id: "aicha-coulibaly", nationality: "Mali", teamId: "chicago-sky", leagueId: "wnba", firstName: "Aicha", lastName: "Coulibaly", position: "PG", jerseyNumber: 34, heightCm: 183, age: 25, overallRating: 66 }),
  mkPlayer({ id: "sydney-taylor", teamId: "chicago-sky", leagueId: "wnba", firstName: "Sydney", lastName: "Taylor", position: "SG", jerseyNumber: 12, heightCm: 175, age: 25, overallRating: 74 }),
  mkPlayer({ id: "rachel-banham", teamId: "chicago-sky", leagueId: "wnba", firstName: "Rachel", lastName: "Banham", position: "PG", jerseyNumber: 24, heightCm: 175, age: 33, overallRating: 68 }),

  // --- Washington Mystics ---
  mkPlayer({ id: "sonia-citron", teamId: "washington-mystics", leagueId: "wnba", firstName: "Sonia", lastName: "Citron", position: "SG", jerseyNumber: 3, heightCm: 185, age: 22, overallRating: 78 }),
  mkPlayer({ id: "shakira-austin", teamId: "washington-mystics", leagueId: "wnba", firstName: "Shakira", lastName: "Austin", position: "C", jerseyNumber: 0, heightCm: 196, age: 26, overallRating: 77 }),
  mkPlayer({ id: "kiki-iriafen", teamId: "washington-mystics", leagueId: "wnba", firstName: "Kiki", lastName: "Iriafen", position: "PF", jerseyNumber: 44, heightCm: 191, age: 23, overallRating: 78 }),
  mkPlayer({ id: "lauren-betts", teamId: "washington-mystics", leagueId: "wnba", firstName: "Lauren", lastName: "Betts", position: "C", jerseyNumber: 51, heightCm: 201, age: 22, overallRating: 79 }),
  mkPlayer({ id: "georgia-amoore", nationality: "Australie", teamId: "washington-mystics", leagueId: "wnba", firstName: "Georgia", lastName: "Amoore", position: "PG", jerseyNumber: 14, heightCm: 168, age: 25, overallRating: 74 }),
  mkPlayer({ id: "cotie-mcmahon", teamId: "washington-mystics", leagueId: "wnba", firstName: "Cotie", lastName: "McMahon", position: "SF", jerseyNumber: 32, heightCm: 183, age: 22, overallRating: 70 }),
  mkPlayer({ id: "michaela-onyenwere", teamId: "washington-mystics", leagueId: "wnba", firstName: "Michaela", lastName: "Onyenwere", position: "SF", jerseyNumber: 24, heightCm: 183, age: 26, overallRating: 71 }),
  mkPlayer({ id: "angela-dugalic", nationality: "Serbie", teamId: "washington-mystics", leagueId: "wnba", firstName: "Angela", lastName: "Dugalić", position: "PF", jerseyNumber: 33, heightCm: 193, age: 24, overallRating: 67 }),
  mkPlayer({ id: "betnijah-laney-hamilton", teamId: "washington-mystics", leagueId: "wnba", firstName: "Betnijah", lastName: "Laney-Hamilton", position: "SF", jerseyNumber: 5, heightCm: 183, age: 32, overallRating: 68 }),
  mkPlayer({ id: "lucy-olsen", teamId: "washington-mystics", leagueId: "wnba", firstName: "Lucy", lastName: "Olsen", position: "PG", jerseyNumber: 2, heightCm: 178, age: 23, overallRating: 65 }),
  mkPlayer({ id: "cassandre-prosper", nationality: "Canada", teamId: "washington-mystics", leagueId: "wnba", firstName: "Cassandre", lastName: "Prosper", position: "SF", jerseyNumber: 18, heightCm: 191, age: 21, overallRating: 61 }),
  mkPlayer({ id: "alicia-florez", nationality: "Espagne", teamId: "washington-mystics", leagueId: "wnba", firstName: "Alicia", lastName: "Flórez", position: "PG", jerseyNumber: 2, heightCm: 175, age: 22, overallRating: 60 }),

  // --- Dallas Wings ---
  mkPlayer({ id: "paige-bueckers", teamId: "dallas-wings", leagueId: "wnba", firstName: "Paige", lastName: "Bueckers", position: "PG", jerseyNumber: 5, heightCm: 183, age: 24, overallRating: 90 }),
  mkPlayer({ id: "arike-ogunbowale", teamId: "dallas-wings", leagueId: "wnba", firstName: "Arike", lastName: "Ogunbowale", position: "SG", jerseyNumber: 24, heightCm: 173, age: 29, overallRating: 87 }),
  mkPlayer({ id: "azzi-fudd", teamId: "dallas-wings", leagueId: "wnba", firstName: "Azzi", lastName: "Fudd", position: "SG", jerseyNumber: 35, heightCm: 180, age: 23, overallRating: 76 }),
  mkPlayer({ id: "alanna-smith", nationality: "Australie", teamId: "dallas-wings", leagueId: "wnba", firstName: "Alanna", lastName: "Smith", position: "C", jerseyNumber: 8, heightCm: 193, age: 30, overallRating: 76 }),
  mkPlayer({ id: "maddy-siegrist", teamId: "dallas-wings", leagueId: "wnba", firstName: "Maddy", lastName: "Siegrist", position: "PF", jerseyNumber: 32, heightCm: 188, age: 25, overallRating: 73 }),
  mkPlayer({ id: "aziaha-james", teamId: "dallas-wings", leagueId: "wnba", firstName: "Aziaha", lastName: "James", position: "SG", jerseyNumber: 32, heightCm: 178, age: 23, overallRating: 70 }),
  mkPlayer({ id: "jessica-shepard", teamId: "dallas-wings", leagueId: "wnba", firstName: "Jessica", lastName: "Shepard", position: "PF", jerseyNumber: 9, heightCm: 193, age: 30, overallRating: 68 }),
  mkPlayer({ id: "odyssey-sims", teamId: "dallas-wings", leagueId: "wnba", firstName: "Odyssey", lastName: "Sims", position: "PG", jerseyNumber: 1, heightCm: 173, age: 34, overallRating: 69 }),
  mkPlayer({ id: "awak-kuier", nationality: "Finlande", teamId: "dallas-wings", leagueId: "wnba", firstName: "Awak", lastName: "Kuier", position: "PF", jerseyNumber: 11, heightCm: 193, age: 25, overallRating: 66 }),
  mkPlayer({ id: "li-yueru", nationality: "Chine", teamId: "dallas-wings", leagueId: "wnba", firstName: "Li", lastName: "Yueru", position: "C", jerseyNumber: 26, heightCm: 201, age: 27, overallRating: 65 }),
  mkPlayer({ id: "alysha-clark", teamId: "dallas-wings", leagueId: "wnba", firstName: "Alysha", lastName: "Clark", position: "SF", jerseyNumber: 7, heightCm: 180, age: 39, overallRating: 58 }),
  mkPlayer({ id: "costanza-verona", nationality: "Italie", teamId: "dallas-wings", leagueId: "wnba", firstName: "Costanza", lastName: "Verona", position: "PG", jerseyNumber: 6, heightCm: 168, age: 27, overallRating: 50 }),

  // --- Los Angeles Sparks ---
  mkPlayer({ id: "cameron-brink", teamId: "los-angeles-sparks", leagueId: "wnba", firstName: "Cameron", lastName: "Brink", position: "PF", jerseyNumber: 22, heightCm: 193, age: 24, overallRating: 79, injuryRisk: 50 }),
  mkPlayer({ id: "dearica-hamby", teamId: "los-angeles-sparks", leagueId: "wnba", firstName: "Dearica", lastName: "Hamby", position: "PF", jerseyNumber: 5, heightCm: 191, age: 32, overallRating: 79 }),
  mkPlayer({ id: "nneka-ogwumike", teamId: "los-angeles-sparks", leagueId: "wnba", firstName: "Nneka", lastName: "Ogwumike", position: "PF", jerseyNumber: 30, heightCm: 188, age: 36, overallRating: 82 }),
  mkPlayer({ id: "ariel-atkins", teamId: "los-angeles-sparks", leagueId: "wnba", firstName: "Ariel", lastName: "Atkins", position: "SG", jerseyNumber: 7, heightCm: 173, age: 30, overallRating: 76 }),
  mkPlayer({ id: "kiana-williams", teamId: "los-angeles-sparks", leagueId: "wnba", firstName: "Kiana", lastName: "Williams", position: "PG", jerseyNumber: 23, heightCm: 170, age: 27, overallRating: 58 }),
  mkPlayer({ id: "rae-burrell", teamId: "los-angeles-sparks", leagueId: "wnba", firstName: "Rae", lastName: "Burrell", position: "SF", jerseyNumber: 12, heightCm: 188, age: 26, overallRating: 68 }),
  mkPlayer({ id: "kate-martin", teamId: "los-angeles-sparks", leagueId: "wnba", firstName: "Kate", lastName: "Martin", position: "SG", jerseyNumber: 21, heightCm: 183, age: 25, overallRating: 69 }),
  mkPlayer({ id: "erica-wheeler", teamId: "los-angeles-sparks", leagueId: "wnba", firstName: "Erica", lastName: "Wheeler", position: "PG", jerseyNumber: 17, heightCm: 170, age: 35, overallRating: 66 }),
  mkPlayer({ id: "monique-akoa-makani", nationality: "France", teamId: "los-angeles-sparks", leagueId: "wnba", firstName: "Monique", lastName: "Akoa Makani", position: "PG", jerseyNumber: 8, heightCm: 180, age: 25, overallRating: 68 }),
  mkPlayer({ id: "ji-hyun-park", nationality: "Corée du Sud", teamId: "los-angeles-sparks", leagueId: "wnba", firstName: "Ji-hyun", lastName: "Park", position: "SG", jerseyNumber: 6, heightCm: 185, age: 26, overallRating: 65 }),
  mkPlayer({ id: "chance-gray", teamId: "los-angeles-sparks", leagueId: "wnba", firstName: "Chance", lastName: "Gray", position: "SG", jerseyNumber: 2, heightCm: 175, age: 22, overallRating: 52 }),
  mkPlayer({ id: "emma-cannon", teamId: "los-angeles-sparks", leagueId: "wnba", firstName: "Emma", lastName: "Cannon", position: "PF", jerseyNumber: 32, heightCm: 188, age: 37, overallRating: 54 }),

  // --- Phoenix Mercury ---
  mkPlayer({ id: "alyssa-thomas", teamId: "phoenix-mercury", leagueId: "wnba", firstName: "Alyssa", lastName: "Thomas", position: "PF", jerseyNumber: 25, heightCm: 188, age: 34, overallRating: 88 }),
  mkPlayer({ id: "kahleah-copper", teamId: "phoenix-mercury", leagueId: "wnba", firstName: "Kahleah", lastName: "Copper", position: "SG", jerseyNumber: 2, heightCm: 185, age: 32, overallRating: 82 }),
  mkPlayer({ id: "dewanna-bonner", teamId: "phoenix-mercury", leagueId: "wnba", firstName: "DeWanna", lastName: "Bonner", position: "SG", jerseyNumber: 24, heightCm: 193, age: 39, overallRating: 76 }),
  mkPlayer({ id: "sami-whitcomb", teamId: "phoenix-mercury", leagueId: "wnba", firstName: "Sami", lastName: "Whitcomb", position: "SG", jerseyNumber: 4, heightCm: 178, age: 38, overallRating: 68 }),
  mkPlayer({ id: "natasha-mack", teamId: "phoenix-mercury", leagueId: "wnba", firstName: "Natasha", lastName: "Mack", position: "PF", jerseyNumber: 24, heightCm: 193, age: 29, overallRating: 68 }),
  mkPlayer({ id: "marta-suarez", nationality: "Espagne", teamId: "phoenix-mercury", leagueId: "wnba", firstName: "Marta", lastName: "Suárez", position: "SF", jerseyNumber: 30, heightCm: 191, age: 24, overallRating: 67 }),
  mkPlayer({ id: "kyara-linskens", teamId: "phoenix-mercury", leagueId: "wnba", firstName: "Kyara", lastName: "Linskens", position: "C", jerseyNumber: 9, heightCm: 193, age: 29, overallRating: 65 }),
  mkPlayer({ id: "valeriane-ayayi", nationality: "France", teamId: "phoenix-mercury", leagueId: "wnba", firstName: "Valériane", lastName: "Ayayi", position: "SF", jerseyNumber: 15, heightCm: 185, age: 32, overallRating: 65 }),
  mkPlayer({ id: "lexi-held", teamId: "phoenix-mercury", leagueId: "wnba", firstName: "Lexi", lastName: "Held", position: "SG", jerseyNumber: 3, heightCm: 178, age: 26, overallRating: 64 }),
  mkPlayer({ id: "kara-dunn", teamId: "phoenix-mercury", leagueId: "wnba", firstName: "Kara", lastName: "Dunn", position: "PG", jerseyNumber: 11, heightCm: 180, age: 22, overallRating: 64 }),
  mkPlayer({ id: "noemie-brochant", nationality: "France", teamId: "phoenix-mercury", leagueId: "wnba", firstName: "Noémie", lastName: "Brochant", position: "SF", jerseyNumber: 1, heightCm: 180, age: 26, overallRating: 62 }),
  mkPlayer({ id: "kelsey-plum", teamId: "phoenix-mercury", leagueId: "wnba", firstName: "Kelsey", lastName: "Plum", position: "PG", jerseyNumber: 0, heightCm: 173, age: 32, overallRating: 84 }),

  // --- Golden State Valkyries ---
  mkPlayer({ id: "kayla-thornton", teamId: "golden-state-valkyries", leagueId: "wnba", firstName: "Kayla", lastName: "Thornton", position: "SF", jerseyNumber: 6, heightCm: 185, age: 33, overallRating: 77 }),
  mkPlayer({ id: "veronica-burton", teamId: "golden-state-valkyries", leagueId: "wnba", firstName: "Veronica", lastName: "Burton", position: "PG", jerseyNumber: 22, heightCm: 175, age: 26, overallRating: 74 }),
  mkPlayer({ id: "cecilia-zandalasini", nationality: "Italie", teamId: "golden-state-valkyries", leagueId: "wnba", firstName: "Cecilia", lastName: "Zandalasini", position: "SF", jerseyNumber: 5, heightCm: 188, age: 30, overallRating: 73 }),
  mkPlayer({ id: "janelle-salaun", nationality: "France", teamId: "golden-state-valkyries", leagueId: "wnba", firstName: "Janelle", lastName: "Salaün", position: "SF", jerseyNumber: 13, heightCm: 188, age: 23, overallRating: 70 }),
  mkPlayer({ id: "iliana-rupert", nationality: "France", teamId: "golden-state-valkyries", leagueId: "wnba", firstName: "Iliana", lastName: "Rupert", position: "C", jerseyNumber: 15, heightCm: 193, age: 25, overallRating: 68 }),
  mkPlayer({ id: "gabby-williams", teamId: "golden-state-valkyries", leagueId: "wnba", firstName: "Gabby", lastName: "Williams", position: "SF", jerseyNumber: 9, heightCm: 178, age: 30, overallRating: 79 }),
  mkPlayer({ id: "kaitlyn-chen", teamId: "golden-state-valkyries", leagueId: "wnba", firstName: "Kaitlyn", lastName: "Chen", position: "PG", jerseyNumber: 21, heightCm: 175, age: 24, overallRating: 65 }),
  mkPlayer({ id: "kiah-stokes", teamId: "golden-state-valkyries", leagueId: "wnba", firstName: "Kiah", lastName: "Stokes", position: "C", jerseyNumber: 41, heightCm: 191, age: 33, overallRating: 65 }),
  mkPlayer({ id: "laeticia-amihere", nationality: "Canada", teamId: "golden-state-valkyries", leagueId: "wnba", firstName: "Laeticia", lastName: "Amihere", position: "PF", jerseyNumber: 4, heightCm: 191, age: 25, overallRating: 66 }),
  mkPlayer({ id: "tiffany-hayes", teamId: "golden-state-valkyries", leagueId: "wnba", firstName: "Tiffany", lastName: "Hayes", position: "SG", jerseyNumber: 15, heightCm: 178, age: 36, overallRating: 68 }),
  mkPlayer({ id: "kaila-charles", teamId: "golden-state-valkyries", leagueId: "wnba", firstName: "Kaila", lastName: "Charles", position: "SG", jerseyNumber: 6, heightCm: 185, age: 28, overallRating: 66 }),
  mkPlayer({ id: "ashten-prechtel", teamId: "golden-state-valkyries", leagueId: "wnba", firstName: "Ashten", lastName: "Prechtel", position: "PF", jerseyNumber: 11, heightCm: 196, age: 25, overallRating: 58 }),
];
