import type { Player } from "@/lib/types";
import { mkPlayer } from "./player-helpers";

// Effectifs à jour au 8 août 2026 (intersaison 2026-27) — vérifiés via
// recherche web (Wikipédia, pages de saison par équipe), meilleur effort à
// une date donnée : la ligue continue de bouger (signatures/coupures
// tardives), donc de petits écarts sont possibles dès la prochaine fenêtre
// de transactions.
export const playersNba: Player[] = [
  // --- Lakers ---
  mkPlayer({ id: "luka-doncic", nationality: "Slovénie", teamId: "lal", leagueId: "nba", firstName: "Luka", lastName: "Dončić", position: "PG", jerseyNumber: 77, heightCm: 203, age: 27, overallRating: 96 }),
  mkPlayer({ id: "austin-reaves", teamId: "lal", leagueId: "nba", firstName: "Austin", lastName: "Reaves", position: "SG", jerseyNumber: 15, heightCm: 196, age: 28, overallRating: 84 }),
  mkPlayer({ id: "quentin-grimes", teamId: "lal", leagueId: "nba", firstName: "Quentin", lastName: "Grimes", position: "SG", jerseyNumber: 5, heightCm: 193, age: 26, overallRating: 78 }),
  mkPlayer({ id: "walker-kessler", teamId: "lal", leagueId: "nba", firstName: "Walker", lastName: "Kessler", position: "C", jerseyNumber: 14, heightCm: 218, age: 25, overallRating: 79 }),
  mkPlayer({ id: "jarred-vanderbilt", teamId: "lal", leagueId: "nba", firstName: "Jarred", lastName: "Vanderbilt", position: "PF", jerseyNumber: 2, heightCm: 201, age: 27, overallRating: 73 }),
  mkPlayer({ id: "dalton-knecht", teamId: "lal", leagueId: "nba", firstName: "Dalton", lastName: "Knecht", position: "SG", jerseyNumber: 4, heightCm: 198, age: 25, overallRating: 74 }),
  mkPlayer({ id: "bronny-james", teamId: "lal", leagueId: "nba", firstName: "Bronny", lastName: "James", position: "PG", jerseyNumber: 9, heightCm: 188, age: 21, overallRating: 66 }),
  mkPlayer({ id: "kevon-looney", teamId: "lal", leagueId: "nba", firstName: "Kevon", lastName: "Looney", position: "C", jerseyNumber: 55, heightCm: 206, age: 30, overallRating: 70 }),
  mkPlayer({ id: "collin-sexton", teamId: "lal", leagueId: "nba", firstName: "Collin", lastName: "Sexton", position: "PG", jerseyNumber: 10, heightCm: 190, age: 27, overallRating: 76 }),
  mkPlayer({ id: "jake-laravia", teamId: "lal", leagueId: "nba", firstName: "Jake", lastName: "LaRavia", position: "SF", jerseyNumber: 12, heightCm: 201, age: 24, overallRating: 71 }),

  // --- Celtics ---
  mkPlayer({ id: "jayson-tatum", teamId: "bos", leagueId: "nba", firstName: "Jayson", lastName: "Tatum", position: "SF", jerseyNumber: 0, heightCm: 203, age: 28, overallRating: 95 }),
  mkPlayer({ id: "paul-george", teamId: "bos", leagueId: "nba", firstName: "Paul", lastName: "George", position: "SF", jerseyNumber: 13, heightCm: 201, age: 36, overallRating: 79, injuryRisk: 68 }),
  mkPlayer({ id: "derrick-white", teamId: "bos", leagueId: "nba", firstName: "Derrick", lastName: "White", position: "PG", jerseyNumber: 9, heightCm: 196, age: 32, overallRating: 85 }),
  mkPlayer({ id: "mike-conley", teamId: "bos", leagueId: "nba", firstName: "Mike", lastName: "Conley", position: "PG", jerseyNumber: 44, heightCm: 185, age: 38, overallRating: 73 }),
  mkPlayer({ id: "sam-hauser", teamId: "bos", leagueId: "nba", firstName: "Sam", lastName: "Hauser", position: "SF", jerseyNumber: 30, heightCm: 201, age: 28, overallRating: 74 }),
  mkPlayer({ id: "payton-pritchard", teamId: "bos", leagueId: "nba", firstName: "Payton", lastName: "Pritchard", position: "PG", jerseyNumber: 11, heightCm: 185, age: 28, overallRating: 78 }),
  mkPlayer({ id: "hugo-gonzalez", nationality: "Espagne", teamId: "bos", leagueId: "nba", firstName: "Hugo", lastName: "González", position: "SG", jerseyNumber: 28, heightCm: 198, age: 20, overallRating: 71 }),
  mkPlayer({ id: "neemias-queta", teamId: "bos", leagueId: "nba", firstName: "Neemias", lastName: "Queta", position: "C", jerseyNumber: 88, heightCm: 213, age: 27, overallRating: 73 }),
  mkPlayer({ id: "mitchell-robinson", teamId: "bos", leagueId: "nba", firstName: "Mitchell", lastName: "Robinson", position: "C", jerseyNumber: 4, heightCm: 213, age: 28, overallRating: 75 }),
  mkPlayer({ id: "luka-garza", teamId: "bos", leagueId: "nba", firstName: "Luka", lastName: "Garza", position: "SF", jerseyNumber: 52, heightCm: 208, age: 27, overallRating: 68 }),

  // --- Warriors ---
  mkPlayer({ id: "stephen-curry", teamId: "gsw", leagueId: "nba", firstName: "Stephen", lastName: "Curry", position: "PG", jerseyNumber: 30, heightCm: 188, age: 38, overallRating: 93, injuryRisk: 40 }),
  mkPlayer({ id: "jimmy-butler", teamId: "gsw", leagueId: "nba", firstName: "Jimmy", lastName: "Butler", position: "SF", jerseyNumber: 10, heightCm: 198, age: 36, overallRating: 84, injuryRisk: 55 }),
  mkPlayer({ id: "draymond-green", teamId: "gsw", leagueId: "nba", firstName: "Draymond", lastName: "Green", position: "PF", jerseyNumber: 23, heightCm: 198, age: 36, overallRating: 79 }),
  mkPlayer({ id: "kristaps-porzingis", nationality: "Lettonie", teamId: "gsw", leagueId: "nba", firstName: "Kristaps", lastName: "Porziņģis", position: "C", jerseyNumber: 8, heightCm: 221, age: 31, overallRating: 82, injuryRisk: 78 }),
  mkPlayer({ id: "al-horford", teamId: "gsw", leagueId: "nba", firstName: "Al", lastName: "Horford", position: "PF", jerseyNumber: 8, heightCm: 206, age: 40, overallRating: 71 }),
  mkPlayer({ id: "brandin-podziemski", teamId: "gsw", leagueId: "nba", firstName: "Brandin", lastName: "Podziemski", position: "SG", jerseyNumber: 2, heightCm: 193, age: 23, overallRating: 77 }),
  mkPlayer({ id: "moses-moody", teamId: "gsw", leagueId: "nba", firstName: "Moses", lastName: "Moody", position: "SG", jerseyNumber: 4, heightCm: 196, age: 24, overallRating: 75 }),
  mkPlayer({ id: "gary-payton-ii", teamId: "gsw", leagueId: "nba", firstName: "Gary", lastName: "Payton II", position: "SG", jerseyNumber: 8, heightCm: 188, age: 33, overallRating: 71 }),
  mkPlayer({ id: "de-anthony-melton", teamId: "gsw", leagueId: "nba", firstName: "De'Anthony", lastName: "Melton", position: "SG", jerseyNumber: 8, heightCm: 188, age: 28, overallRating: 70 }),
  mkPlayer({ id: "will-richard", teamId: "gsw", leagueId: "nba", firstName: "Will", lastName: "Richard", position: "SG", jerseyNumber: 8, heightCm: 191, age: 23, overallRating: 68 }),

  // --- Bucks ---
  mkPlayer({ id: "kyle-kuzma", teamId: "mil", leagueId: "nba", firstName: "Kyle", lastName: "Kuzma", position: "SF", jerseyNumber: 18, heightCm: 203, age: 31, overallRating: 76 }),
  mkPlayer({ id: "myles-turner", teamId: "mil", leagueId: "nba", firstName: "Myles", lastName: "Turner", position: "PF", jerseyNumber: 3, heightCm: 211, age: 30, overallRating: 82 }),
  mkPlayer({ id: "tyler-herro", teamId: "mil", leagueId: "nba", firstName: "Tyler", lastName: "Herro", position: "SG", jerseyNumber: 11, heightCm: 196, age: 26, overallRating: 86 }),
  mkPlayer({ id: "kevin-porter-jr", teamId: "mil", leagueId: "nba", firstName: "Kevin", lastName: "Porter Jr.", position: "SG", jerseyNumber: 7, heightCm: 196, age: 26, overallRating: 74 }),
  mkPlayer({ id: "gary-trent-jr", teamId: "mil", leagueId: "nba", firstName: "Gary", lastName: "Trent Jr.", position: "SG", jerseyNumber: 5, heightCm: 196, age: 27, overallRating: 74 }),
  mkPlayer({ id: "caris-levert", teamId: "mil", leagueId: "nba", firstName: "Caris", lastName: "LeVert", position: "SF", jerseyNumber: 12, heightCm: 201, age: 32, overallRating: 74 }),
  mkPlayer({ id: "aj-green", teamId: "mil", leagueId: "nba", firstName: "AJ", lastName: "Green", position: "SG", jerseyNumber: 20, heightCm: 196, age: 27, overallRating: 73 }),
  mkPlayer({ id: "kelel-ware", teamId: "mil", leagueId: "nba", firstName: "Kel'el", lastName: "Ware", position: "C", jerseyNumber: 9, heightCm: 213, age: 22, overallRating: 78 }),
  mkPlayer({ id: "jaime-jaquez-jr", teamId: "mil", leagueId: "nba", firstName: "Jaime", lastName: "Jaquez Jr.", position: "SG", jerseyNumber: 24, heightCm: 198, age: 25, overallRating: 74 }),
  mkPlayer({ id: "ryan-rollins", teamId: "mil", leagueId: "nba", firstName: "Ryan", lastName: "Rollins", position: "SG", jerseyNumber: 13, heightCm: 190, age: 24, overallRating: 73 }),

  // --- Nuggets ---
  mkPlayer({ id: "nikola-jokic", nationality: "Serbie", teamId: "den", leagueId: "nba", firstName: "Nikola", lastName: "Jokić", position: "C", jerseyNumber: 15, heightCm: 211, age: 31, overallRating: 98, injuryRisk: 15 }),
  mkPlayer({ id: "jamal-murray", nationality: "Canada", teamId: "den", leagueId: "nba", firstName: "Jamal", lastName: "Murray", position: "PG", jerseyNumber: 27, heightCm: 191, age: 29, overallRating: 88, injuryRisk: 68 }),
  mkPlayer({ id: "aaron-gordon", teamId: "den", leagueId: "nba", firstName: "Aaron", lastName: "Gordon", position: "PF", jerseyNumber: 50, heightCm: 203, age: 30, overallRating: 82 }),
  mkPlayer({ id: "cameron-johnson", teamId: "den", leagueId: "nba", firstName: "Cameron", lastName: "Johnson", position: "SF", jerseyNumber: 1, heightCm: 203, age: 30, overallRating: 78 }),
  mkPlayer({ id: "christian-braun", teamId: "den", leagueId: "nba", firstName: "Christian", lastName: "Braun", position: "SG", jerseyNumber: 0, heightCm: 196, age: 25, overallRating: 78 }),
  mkPlayer({ id: "tyus-jones", teamId: "den", leagueId: "nba", firstName: "Tyus", lastName: "Jones", position: "SG", jerseyNumber: 21, heightCm: 183, age: 30, overallRating: 75 }),
  mkPlayer({ id: "peyton-watson", teamId: "den", leagueId: "nba", firstName: "Peyton", lastName: "Watson", position: "SF", jerseyNumber: 8, heightCm: 203, age: 23, overallRating: 75 }),
  mkPlayer({ id: "zeke-nnaji", teamId: "den", leagueId: "nba", firstName: "Zeke", lastName: "Nnaji", position: "PF", jerseyNumber: 22, heightCm: 206, age: 25, overallRating: 70 }),
  mkPlayer({ id: "marvin-bagley-iii", teamId: "den", leagueId: "nba", firstName: "Marvin", lastName: "Bagley III", position: "SF", jerseyNumber: 35, heightCm: 208, age: 27, overallRating: 72 }),
  mkPlayer({ id: "daron-holmes-ii", teamId: "den", leagueId: "nba", firstName: "DaRon", lastName: "Holmes II", position: "SF", jerseyNumber: 12, heightCm: 206, age: 22, overallRating: 71 }),

  // --- Knicks ---
  mkPlayer({ id: "jalen-brunson", teamId: "nyk", leagueId: "nba", firstName: "Jalen", lastName: "Brunson", position: "PG", jerseyNumber: 11, heightCm: 185, age: 30, overallRating: 91 }),
  mkPlayer({ id: "karl-anthony-towns", teamId: "nyk", leagueId: "nba", firstName: "Karl-Anthony", lastName: "Towns", position: "C", jerseyNumber: 32, heightCm: 213, age: 30, overallRating: 87, injuryRisk: 50 }),
  mkPlayer({ id: "og-anunoby", teamId: "nyk", leagueId: "nba", firstName: "OG", lastName: "Anunoby", position: "SF", jerseyNumber: 8, heightCm: 198, age: 29, overallRating: 84 }),
  mkPlayer({ id: "mikal-bridges", teamId: "nyk", leagueId: "nba", firstName: "Mikal", lastName: "Bridges", position: "SF", jerseyNumber: 25, heightCm: 198, age: 30, overallRating: 83, injuryRisk: 10 }),
  mkPlayer({ id: "josh-hart", teamId: "nyk", leagueId: "nba", firstName: "Josh", lastName: "Hart", position: "SG", jerseyNumber: 3, heightCm: 196, age: 31, overallRating: 79 }),
  mkPlayer({ id: "andre-drummond", teamId: "nyk", leagueId: "nba", firstName: "Andre", lastName: "Drummond", position: "C", jerseyNumber: 0, heightCm: 208, age: 33, overallRating: 73 }),
  mkPlayer({ id: "miles-mcbride", teamId: "nyk", leagueId: "nba", firstName: "Miles", lastName: "McBride", position: "PG", jerseyNumber: 2, heightCm: 185, age: 26, overallRating: 75 }),
  mkPlayer({ id: "jordan-clarkson", teamId: "nyk", leagueId: "nba", firstName: "Jordan", lastName: "Clarkson", position: "SG", jerseyNumber: 0, heightCm: 196, age: 34, overallRating: 72 }),
  mkPlayer({ id: "jose-alvarado", teamId: "nyk", leagueId: "nba", firstName: "Jose", lastName: "Alvarado", position: "PG", jerseyNumber: 5, heightCm: 185, age: 28, overallRating: 72 }),
  mkPlayer({ id: "landry-shamet", teamId: "nyk", leagueId: "nba", firstName: "Landry", lastName: "Shamet", position: "SG", jerseyNumber: 44, heightCm: 196, age: 29, overallRating: 69 }),

  // --- Heat ---
  mkPlayer({ id: "bam-adebayo", teamId: "mia", leagueId: "nba", firstName: "Bam", lastName: "Adebayo", position: "C", jerseyNumber: 13, heightCm: 206, age: 29, overallRating: 88 }),
  mkPlayer({ id: "giannis-antetokounmpo", nationality: "Grèce", teamId: "mia", leagueId: "nba", firstName: "Giannis", lastName: "Antetokounmpo", position: "PF", jerseyNumber: 7, heightCm: 211, age: 31, overallRating: 97, injuryRisk: 28 }),
  mkPlayer({ id: "bobby-portis", teamId: "mia", leagueId: "nba", firstName: "Bobby", lastName: "Portis", position: "SF", jerseyNumber: 95, heightCm: 206, age: 31, overallRating: 77 }),
  mkPlayer({ id: "andrew-wiggins", nationality: "Canada", teamId: "mia", leagueId: "nba", firstName: "Andrew", lastName: "Wiggins", position: "SF", jerseyNumber: 22, heightCm: 201, age: 31, overallRating: 76 }),
  mkPlayer({ id: "davion-mitchell", teamId: "mia", leagueId: "nba", firstName: "Davion", lastName: "Mitchell", position: "PG", jerseyNumber: 2, heightCm: 188, age: 28, overallRating: 75 }),
  mkPlayer({ id: "nikola-jovic", nationality: "Serbie", teamId: "mia", leagueId: "nba", firstName: "Nikola", lastName: "Jović", position: "SF", jerseyNumber: 5, heightCm: 208, age: 23, overallRating: 76, injuryRisk: 45 }),
  mkPlayer({ id: "pelle-larsson", nationality: "Suède", teamId: "mia", leagueId: "nba", firstName: "Pelle", lastName: "Larsson", position: "SG", jerseyNumber: 9, heightCm: 196, age: 25, overallRating: 71 }),
  mkPlayer({ id: "tim-hardaway-jr", teamId: "mia", leagueId: "nba", firstName: "Tim", lastName: "Hardaway Jr.", position: "SG", jerseyNumber: 10, heightCm: 196, age: 34, overallRating: 71 }),
  mkPlayer({ id: "simone-fontecchio", nationality: "Italie", teamId: "mia", leagueId: "nba", firstName: "Simone", lastName: "Fontecchio", position: "SF", jerseyNumber: 0, heightCm: 201, age: 30, overallRating: 71 }),
  mkPlayer({ id: "vladislav-goldin", nationality: "Russie", teamId: "mia", leagueId: "nba", firstName: "Vladislav", lastName: "Goldin", position: "C", jerseyNumber: 50, heightCm: 213, age: 25, overallRating: 68 }),

  // --- 76ers ---
  mkPlayer({ id: "joel-embiid", nationality: "Cameroun", teamId: "phi", leagueId: "nba", firstName: "Joel", lastName: "Embiid", position: "C", jerseyNumber: 21, heightCm: 213, age: 32, overallRating: 87, injuryRisk: 88 }),
  mkPlayer({ id: "tyrese-maxey", teamId: "phi", leagueId: "nba", firstName: "Tyrese", lastName: "Maxey", position: "PG", jerseyNumber: 0, heightCm: 185, age: 25, overallRating: 90 }),
  mkPlayer({ id: "lebron-james", teamId: "phi", leagueId: "nba", firstName: "LeBron", lastName: "James", position: "SF", jerseyNumber: 23, heightCm: 206, age: 41, overallRating: 87, injuryRisk: 60 }),
  mkPlayer({ id: "jaylen-brown", teamId: "phi", leagueId: "nba", firstName: "Jaylen", lastName: "Brown", position: "SG", jerseyNumber: 7, heightCm: 198, age: 29, overallRating: 89 }),
  mkPlayer({ id: "anfernee-simons", teamId: "phi", leagueId: "nba", firstName: "Anfernee", lastName: "Simons", position: "SG", jerseyNumber: 5, heightCm: 190, age: 27, overallRating: 79 }),
  mkPlayer({ id: "kentavious-caldwell-pope", teamId: "phi", leagueId: "nba", firstName: "Kentavious", lastName: "Caldwell-Pope", position: "SG", jerseyNumber: 1, heightCm: 196, age: 33, overallRating: 76 }),
  mkPlayer({ id: "vj-edgecombe", teamId: "phi", leagueId: "nba", firstName: "V.J.", lastName: "Edgecombe", position: "SG", jerseyNumber: 77, heightCm: 193, age: 21, overallRating: 76 }),
  mkPlayer({ id: "justin-edwards", teamId: "phi", leagueId: "nba", firstName: "Justin", lastName: "Edwards", position: "SF", jerseyNumber: 11, heightCm: 201, age: 22, overallRating: 71 }),
  mkPlayer({ id: "adem-bona", nationality: "Nigeria", teamId: "phi", leagueId: "nba", firstName: "Adem", lastName: "Bona", position: "PF", jerseyNumber: 30, heightCm: 208, age: 23, overallRating: 72 }),
  mkPlayer({ id: "jabari-walker", teamId: "phi", leagueId: "nba", firstName: "Jabari", lastName: "Walker", position: "SF", jerseyNumber: 33, heightCm: 201, age: 24, overallRating: 70 }),

  // --- Cavaliers ---
  mkPlayer({ id: "donovan-mitchell", teamId: "cle", leagueId: "nba", firstName: "Donovan", lastName: "Mitchell", position: "PG", jerseyNumber: 45, heightCm: 185, age: 29, overallRating: 91 }),
  mkPlayer({ id: "evan-mobley", teamId: "cle", leagueId: "nba", firstName: "Evan", lastName: "Mobley", position: "C", jerseyNumber: 4, heightCm: 211, age: 25, overallRating: 90 }),
  mkPlayer({ id: "jarrett-allen", teamId: "cle", leagueId: "nba", firstName: "Jarrett", lastName: "Allen", position: "C", jerseyNumber: 31, heightCm: 211, age: 28, overallRating: 83 }),
  mkPlayer({ id: "james-harden", teamId: "cle", leagueId: "nba", firstName: "James", lastName: "Harden", position: "PG", jerseyNumber: 1, heightCm: 196, age: 36, overallRating: 82 }),
  mkPlayer({ id: "dennis-schroder", nationality: "Allemagne", teamId: "cle", leagueId: "nba", firstName: "Dennis", lastName: "Schröder", position: "PG", jerseyNumber: 17, heightCm: 185, age: 32, overallRating: 74 }),
  mkPlayer({ id: "max-strus", teamId: "cle", leagueId: "nba", firstName: "Max", lastName: "Strus", position: "SG", jerseyNumber: 1, heightCm: 196, age: 30, overallRating: 77 }),
  mkPlayer({ id: "sam-merrill", teamId: "cle", leagueId: "nba", firstName: "Sam", lastName: "Merrill", position: "SG", jerseyNumber: 5, heightCm: 196, age: 30, overallRating: 72 }),
  mkPlayer({ id: "thomas-bryant", teamId: "cle", leagueId: "nba", firstName: "Thomas", lastName: "Bryant", position: "PF", jerseyNumber: 0, heightCm: 206, age: 29, overallRating: 69 }),
  mkPlayer({ id: "craig-porter-jr", teamId: "cle", leagueId: "nba", firstName: "Craig", lastName: "Porter Jr.", position: "SG", jerseyNumber: 9, heightCm: 185, age: 26, overallRating: 68 }),
  mkPlayer({ id: "jaylon-tyson", teamId: "cle", leagueId: "nba", firstName: "Jaylon", lastName: "Tyson", position: "SG", jerseyNumber: 8, heightCm: 198, age: 23, overallRating: 70 }),

  // --- Magic ---
  mkPlayer({ id: "paolo-banchero", teamId: "orl", leagueId: "nba", firstName: "Paolo", lastName: "Banchero", position: "PF", jerseyNumber: 5, heightCm: 208, age: 23, overallRating: 89 }),
  mkPlayer({ id: "franz-wagner", nationality: "Allemagne", teamId: "orl", leagueId: "nba", firstName: "Franz", lastName: "Wagner", position: "SF", jerseyNumber: 22, heightCm: 203, age: 24, overallRating: 87 }),
  mkPlayer({ id: "desmond-bane", teamId: "orl", leagueId: "nba", firstName: "Desmond", lastName: "Bane", position: "SG", jerseyNumber: 3, heightCm: 196, age: 28, overallRating: 85 }),
  mkPlayer({ id: "jalen-suggs", teamId: "orl", leagueId: "nba", firstName: "Jalen", lastName: "Suggs", position: "PG", jerseyNumber: 4, heightCm: 196, age: 25, overallRating: 80 }),
  mkPlayer({ id: "nikola-vucevic", nationality: "Monténégro", teamId: "orl", leagueId: "nba", firstName: "Nikola", lastName: "Vučević", position: "C", jerseyNumber: 9, heightCm: 211, age: 35, overallRating: 79 }),
  mkPlayer({ id: "wendell-carter-jr", teamId: "orl", leagueId: "nba", firstName: "Wendell", lastName: "Carter Jr.", position: "C", jerseyNumber: 34, heightCm: 208, age: 27, overallRating: 76 }),
  mkPlayer({ id: "anthony-black", teamId: "orl", leagueId: "nba", firstName: "Anthony", lastName: "Black", position: "PG", jerseyNumber: 0, heightCm: 196, age: 22, overallRating: 74 }),
  mkPlayer({ id: "tristan-da-silva", nationality: "Allemagne", teamId: "orl", leagueId: "nba", firstName: "Tristan", lastName: "da Silva", position: "SF", jerseyNumber: 23, heightCm: 203, age: 25, overallRating: 74 }),
  mkPlayer({ id: "goga-bitadze", nationality: "Géorgie", teamId: "orl", leagueId: "nba", firstName: "Goga", lastName: "Bitadze", position: "C", jerseyNumber: 35, heightCm: 213, age: 27, overallRating: 71 }),
  mkPlayer({ id: "jonathan-isaac", teamId: "orl", leagueId: "nba", firstName: "Jonathan", lastName: "Isaac", position: "SF", jerseyNumber: 1, heightCm: 208, age: 28, overallRating: 70, injuryRisk: 70 }),

  // --- Pacers ---
  mkPlayer({ id: "tyrese-haliburton", teamId: "ind", leagueId: "nba", firstName: "Tyrese", lastName: "Haliburton", position: "PG", jerseyNumber: 0, heightCm: 196, age: 26, overallRating: 88, injuryRisk: 45 }),
  mkPlayer({ id: "pascal-siakam", teamId: "ind", leagueId: "nba", firstName: "Pascal", lastName: "Siakam", position: "PF", jerseyNumber: 43, heightCm: 203, age: 32, overallRating: 85 }),
  mkPlayer({ id: "kelly-oubre-jr", teamId: "ind", leagueId: "nba", firstName: "Kelly", lastName: "Oubre Jr.", position: "SG", jerseyNumber: 10, heightCm: 201, age: 30, overallRating: 78 }),
  mkPlayer({ id: "andrew-nembhard", teamId: "ind", leagueId: "nba", firstName: "Andrew", lastName: "Nembhard", position: "PG", jerseyNumber: 2, heightCm: 196, age: 26, overallRating: 78 }),
  mkPlayer({ id: "aaron-nesmith", teamId: "ind", leagueId: "nba", firstName: "Aaron", lastName: "Nesmith", position: "SG", jerseyNumber: 23, heightCm: 198, age: 26, overallRating: 79 }),
  mkPlayer({ id: "obi-toppin", teamId: "ind", leagueId: "nba", firstName: "Obi", lastName: "Toppin", position: "SF", jerseyNumber: 1, heightCm: 206, age: 28, overallRating: 76 }),
  mkPlayer({ id: "jarace-walker", teamId: "ind", leagueId: "nba", firstName: "Jarace", lastName: "Walker", position: "SF", jerseyNumber: 5, heightCm: 203, age: 23, overallRating: 74 }),
  mkPlayer({ id: "larry-nance-jr", teamId: "ind", leagueId: "nba", firstName: "Larry", lastName: "Nance Jr.", position: "PF", jerseyNumber: 22, heightCm: 198, age: 33, overallRating: 71 }),
  mkPlayer({ id: "tj-mcconnell", teamId: "ind", leagueId: "nba", firstName: "T.J.", lastName: "McConnell", position: "SG", jerseyNumber: 9, heightCm: 185, age: 34, overallRating: 74 }),
  mkPlayer({ id: "ivica-zubac", nationality: "Croatie", teamId: "ind", leagueId: "nba", firstName: "Ivica", lastName: "Zubac", position: "C", jerseyNumber: 40, heightCm: 216, age: 29, overallRating: 81 }),

  // --- Hawks ---
  mkPlayer({ id: "jalen-johnson", teamId: "atl", leagueId: "nba", firstName: "Jalen", lastName: "Johnson", position: "SF", jerseyNumber: 1, heightCm: 206, age: 24, overallRating: 85 }),
  mkPlayer({ id: "onyeka-okongwu", teamId: "atl", leagueId: "nba", firstName: "Onyeka", lastName: "Okongwu", position: "PF", jerseyNumber: 17, heightCm: 206, age: 25, overallRating: 81 }),
  mkPlayer({ id: "dyson-daniels", nationality: "Australie", teamId: "atl", leagueId: "nba", firstName: "Dyson", lastName: "Daniels", position: "SG", jerseyNumber: 5, heightCm: 201, age: 23, overallRating: 80 }),
  mkPlayer({ id: "nickeil-alexander-walker", nationality: "Canada", teamId: "atl", leagueId: "nba", firstName: "Nickeil", lastName: "Alexander-Walker", position: "SG", jerseyNumber: 7, heightCm: 196, age: 27, overallRating: 77 }),
  mkPlayer({ id: "luguentz-dort", nationality: "Canada", teamId: "atl", leagueId: "nba", firstName: "Luguentz", lastName: "Dort", position: "SG", jerseyNumber: 5, heightCm: 191, age: 27, overallRating: 78 }),
  mkPlayer({ id: "cj-mccollum", teamId: "atl", leagueId: "nba", firstName: "CJ", lastName: "McCollum", position: "SG", jerseyNumber: 3, heightCm: 191, age: 35, overallRating: 76 }),
  mkPlayer({ id: "buddy-hield", teamId: "atl", leagueId: "nba", firstName: "Buddy", lastName: "Hield", position: "SG", jerseyNumber: 8, heightCm: 193, age: 33, overallRating: 75 }),
  mkPlayer({ id: "jock-landale", nationality: "Australie", teamId: "atl", leagueId: "nba", firstName: "Jock", lastName: "Landale", position: "C", jerseyNumber: 31, heightCm: 211, age: 30, overallRating: 71 }),
  mkPlayer({ id: "corey-kispert", teamId: "atl", leagueId: "nba", firstName: "Corey", lastName: "Kispert", position: "SF", jerseyNumber: 24, heightCm: 201, age: 27, overallRating: 72 }),
  mkPlayer({ id: "devin-carter", teamId: "atl", leagueId: "nba", firstName: "Devin", lastName: "Carter", position: "SG", jerseyNumber: 22, heightCm: 191, age: 24, overallRating: 71 }),

  // --- Bulls ---
  mkPlayer({ id: "josh-giddey", nationality: "Australie", teamId: "chi", leagueId: "nba", firstName: "Josh", lastName: "Giddey", position: "PG", jerseyNumber: 3, heightCm: 203, age: 24, overallRating: 83 }),
  mkPlayer({ id: "nic-claxton", teamId: "chi", leagueId: "nba", firstName: "Nic", lastName: "Claxton", position: "C", jerseyNumber: 9, heightCm: 211, age: 27, overallRating: 78 }),
  mkPlayer({ id: "matas-buzelis", teamId: "chi", leagueId: "nba", firstName: "Matas", lastName: "Buzelis", position: "SF", jerseyNumber: 14, heightCm: 208, age: 22, overallRating: 77 }),
  mkPlayer({ id: "norman-powell", teamId: "chi", leagueId: "nba", firstName: "Norman", lastName: "Powell", position: "SG", jerseyNumber: 24, heightCm: 191, age: 33, overallRating: 81 }),
  mkPlayer({ id: "patrick-williams", teamId: "chi", leagueId: "nba", firstName: "Patrick", lastName: "Williams", position: "SF", jerseyNumber: 44, heightCm: 203, age: 25, overallRating: 74 }),
  mkPlayer({ id: "tre-jones", teamId: "chi", leagueId: "nba", firstName: "Tre", lastName: "Jones", position: "PG", jerseyNumber: 30, heightCm: 188, age: 26, overallRating: 72 }),
  mkPlayer({ id: "isaac-okoro", teamId: "chi", leagueId: "nba", firstName: "Isaac", lastName: "Okoro", position: "SG", jerseyNumber: 35, heightCm: 196, age: 25, overallRating: 72 }),
  mkPlayer({ id: "noa-essengue", nationality: "France", teamId: "chi", leagueId: "nba", firstName: "Noa", lastName: "Essengue", position: "SF", jerseyNumber: 2, heightCm: 208, age: 19, overallRating: 71 }),
  mkPlayer({ id: "rob-dillingham", teamId: "chi", leagueId: "nba", firstName: "Rob", lastName: "Dillingham", position: "SG", jerseyNumber: 7, heightCm: 188, age: 21, overallRating: 72 }),
  mkPlayer({ id: "zach-collins", teamId: "chi", leagueId: "nba", firstName: "Zach", lastName: "Collins", position: "PF", jerseyNumber: 12, heightCm: 206, age: 28, overallRating: 70 }),

  // --- Nets ---
  mkPlayer({ id: "michael-porter-jr", teamId: "bkn", leagueId: "nba", firstName: "Michael", lastName: "Porter Jr.", position: "SF", jerseyNumber: 17, heightCm: 208, age: 28, overallRating: 81 }),
  mkPlayer({ id: "julius-randle", teamId: "bkn", leagueId: "nba", firstName: "Julius", lastName: "Randle", position: "PF", jerseyNumber: 30, heightCm: 203, age: 31, overallRating: 82 }),
  mkPlayer({ id: "terance-mann", teamId: "bkn", leagueId: "nba", firstName: "Terance", lastName: "Mann", position: "SG", jerseyNumber: 14, heightCm: 196, age: 30, overallRating: 71 }),
  mkPlayer({ id: "day-ron-sharpe", teamId: "bkn", leagueId: "nba", firstName: "Day'Ron", lastName: "Sharpe", position: "C", jerseyNumber: 20, heightCm: 208, age: 24, overallRating: 71 }),
  mkPlayer({ id: "noah-clowney", teamId: "bkn", leagueId: "nba", firstName: "Noah", lastName: "Clowney", position: "PF", jerseyNumber: 21, heightCm: 208, age: 22, overallRating: 72 }),
  mkPlayer({ id: "egor-demin", nationality: "Russie", teamId: "bkn", leagueId: "nba", firstName: "Egor", lastName: "Dëmin", position: "PG", jerseyNumber: 8, heightCm: 203, age: 20, overallRating: 71 }),
  mkPlayer({ id: "drake-powell", teamId: "bkn", leagueId: "nba", firstName: "Drake", lastName: "Powell", position: "SG", jerseyNumber: 4, heightCm: 196, age: 21, overallRating: 71 }),
  mkPlayer({ id: "ben-saraf", nationality: "Israël", teamId: "bkn", leagueId: "nba", firstName: "Ben", lastName: "Saraf", position: "SG", jerseyNumber: 77, heightCm: 198, age: 20, overallRating: 70 }),
  mkPlayer({ id: "nolan-traore", nationality: "France", teamId: "bkn", leagueId: "nba", firstName: "Nolan", lastName: "Traoré", position: "PG", jerseyNumber: 10, heightCm: 191, age: 20, overallRating: 69 }),
  mkPlayer({ id: "moritz-wagner", nationality: "Allemagne", teamId: "bkn", leagueId: "nba", firstName: "Moritz", lastName: "Wagner", position: "PF", jerseyNumber: 13, heightCm: 211, age: 29, overallRating: 71 }),

  // --- Raptors ---
  mkPlayer({ id: "scottie-barnes", teamId: "tor", leagueId: "nba", firstName: "Scottie", lastName: "Barnes", position: "SF", jerseyNumber: 4, heightCm: 203, age: 25, overallRating: 87 }),
  mkPlayer({ id: "kawhi-leonard", teamId: "tor", leagueId: "nba", firstName: "Kawhi", lastName: "Leonard", position: "SF", jerseyNumber: 2, heightCm: 201, age: 35, overallRating: 84, injuryRisk: 82 }),
  mkPlayer({ id: "rj-barrett", nationality: "Canada", teamId: "tor", leagueId: "nba", firstName: "RJ", lastName: "Barrett", position: "SG", jerseyNumber: 9, heightCm: 198, age: 26, overallRating: 82 }),
  mkPlayer({ id: "immanuel-quickley", teamId: "tor", leagueId: "nba", firstName: "Immanuel", lastName: "Quickley", position: "PG", jerseyNumber: 5, heightCm: 188, age: 27, overallRating: 79 }),
  mkPlayer({ id: "jakob-poeltl", nationality: "Autriche", teamId: "tor", leagueId: "nba", firstName: "Jakob", lastName: "Pöltl", position: "C", jerseyNumber: 19, heightCm: 213, age: 30, overallRating: 78 }),
  mkPlayer({ id: "jamal-shead", teamId: "tor", leagueId: "nba", firstName: "Jamal", lastName: "Shead", position: "PG", jerseyNumber: 23, heightCm: 183, age: 24, overallRating: 71 }),
  mkPlayer({ id: "collin-murray-boyles", teamId: "tor", leagueId: "nba", firstName: "Collin", lastName: "Murray-Boyles", position: "SF", jerseyNumber: 0, heightCm: 201, age: 21, overallRating: 70 }),
  mkPlayer({ id: "kyle-anderson", teamId: "tor", leagueId: "nba", firstName: "Kyle", lastName: "Anderson", position: "SG", jerseyNumber: 0, heightCm: 203, age: 32, overallRating: 71 }),
  mkPlayer({ id: "jamison-battle", teamId: "tor", leagueId: "nba", firstName: "Jamison", lastName: "Battle", position: "SF", jerseyNumber: 0, heightCm: 201, age: 25, overallRating: 69 }),
  mkPlayer({ id: "trayce-jackson-davis", teamId: "tor", leagueId: "nba", firstName: "Trayce", lastName: "Jackson-Davis", position: "SF", jerseyNumber: 0, heightCm: 206, age: 26, overallRating: 70 }),

  // --- Pistons ---
  mkPlayer({ id: "cade-cunningham", teamId: "det", leagueId: "nba", firstName: "Cade", lastName: "Cunningham", position: "PG", jerseyNumber: 2, heightCm: 198, age: 25, overallRating: 91 }),
  mkPlayer({ id: "ausar-thompson", teamId: "det", leagueId: "nba", firstName: "Ausar", lastName: "Thompson", position: "SG", jerseyNumber: 9, heightCm: 201, age: 23, overallRating: 79 }),
  mkPlayer({ id: "john-collins", teamId: "det", leagueId: "nba", firstName: "John", lastName: "Collins", position: "PF", jerseyNumber: 20, heightCm: 203, age: 29, overallRating: 77 }),
  mkPlayer({ id: "jalen-duren", teamId: "det", leagueId: "nba", firstName: "Jalen", lastName: "Duren", position: "C", jerseyNumber: 0, heightCm: 208, age: 22, overallRating: 81 }),
  mkPlayer({ id: "kevin-huerter", teamId: "det", leagueId: "nba", firstName: "Kevin", lastName: "Huerter", position: "SG", jerseyNumber: 27, heightCm: 198, age: 28, overallRating: 73 }),
  mkPlayer({ id: "duncan-robinson", teamId: "det", leagueId: "nba", firstName: "Duncan", lastName: "Robinson", position: "SF", jerseyNumber: 55, heightCm: 201, age: 32, overallRating: 73 }),
  mkPlayer({ id: "ron-holland-ii", teamId: "det", leagueId: "nba", firstName: "Ron", lastName: "Holland II", position: "SF", jerseyNumber: 5, heightCm: 201, age: 21, overallRating: 74 }),
  mkPlayer({ id: "isaiah-joe", teamId: "det", leagueId: "nba", firstName: "Isaiah", lastName: "Joe", position: "SG", jerseyNumber: 17, heightCm: 193, age: 27, overallRating: 71 }),
  mkPlayer({ id: "gary-harris", teamId: "det", leagueId: "nba", firstName: "Gary", lastName: "Harris", position: "SG", jerseyNumber: 14, heightCm: 193, age: 32, overallRating: 70 }),
  mkPlayer({ id: "paul-reed", teamId: "det", leagueId: "nba", firstName: "Paul", lastName: "Reed", position: "SF", jerseyNumber: 7, heightCm: 206, age: 27, overallRating: 70 }),

  // --- Hornets ---
  mkPlayer({ id: "brandon-miller", teamId: "cha", leagueId: "nba", firstName: "Brandon", lastName: "Miller", position: "SG", jerseyNumber: 24, heightCm: 203, age: 24, overallRating: 82 }),
  mkPlayer({ id: "kon-knueppel", teamId: "cha", leagueId: "nba", firstName: "Kon", lastName: "Knueppel", position: "SG", jerseyNumber: 7, heightCm: 198, age: 21, overallRating: 77 }),
  mkPlayer({ id: "coby-white", teamId: "cha", leagueId: "nba", firstName: "Coby", lastName: "White", position: "SG", jerseyNumber: 3, heightCm: 193, age: 26, overallRating: 80 }),
  mkPlayer({ id: "naz-reid", teamId: "cha", leagueId: "nba", firstName: "Naz", lastName: "Reid", position: "PF", jerseyNumber: 0, heightCm: 208, age: 27, overallRating: 79 }),
  mkPlayer({ id: "grayson-allen", teamId: "cha", leagueId: "nba", firstName: "Grayson", lastName: "Allen", position: "SG", jerseyNumber: 8, heightCm: 196, age: 31, overallRating: 76 }),
  mkPlayer({ id: "royce-oneale", teamId: "cha", leagueId: "nba", firstName: "Royce", lastName: "O'Neale", position: "SF", jerseyNumber: 0, heightCm: 198, age: 33, overallRating: 73 }),
  mkPlayer({ id: "ryan-kalkbrenner", teamId: "cha", leagueId: "nba", firstName: "Ryan", lastName: "Kalkbrenner", position: "C", jerseyNumber: 11, heightCm: 216, age: 24, overallRating: 72 }),
  mkPlayer({ id: "tre-mann", teamId: "cha", leagueId: "nba", firstName: "Tre", lastName: "Mann", position: "SG", jerseyNumber: 23, heightCm: 193, age: 25, overallRating: 73 }),
  mkPlayer({ id: "grant-williams", teamId: "cha", leagueId: "nba", firstName: "Grant", lastName: "Williams", position: "SF", jerseyNumber: 2, heightCm: 201, age: 28, overallRating: 72 }),
  mkPlayer({ id: "dorian-finney-smith", teamId: "cha", leagueId: "nba", firstName: "Dorian", lastName: "Finney-Smith", position: "SF", jerseyNumber: 17, heightCm: 201, age: 33, overallRating: 72 }),

  // --- Wizards ---
  mkPlayer({ id: "trae-young", teamId: "was", leagueId: "nba", firstName: "Trae", lastName: "Young", position: "PG", jerseyNumber: 3, heightCm: 185, age: 28, overallRating: 86 }),
  mkPlayer({ id: "anthony-davis", teamId: "was", leagueId: "nba", firstName: "Anthony", lastName: "Davis", position: "PF", jerseyNumber: 23, heightCm: 208, age: 33, overallRating: 87, injuryRisk: 78 }),
  mkPlayer({ id: "bilal-coulibaly", nationality: "France", teamId: "was", leagueId: "nba", firstName: "Bilal", lastName: "Coulibaly", position: "SF", jerseyNumber: 0, heightCm: 201, age: 22, overallRating: 78 }),
  mkPlayer({ id: "alex-sarr", nationality: "France", teamId: "was", leagueId: "nba", firstName: "Alex", lastName: "Sarr", position: "C", jerseyNumber: 20, heightCm: 213, age: 21, overallRating: 78 }),
  mkPlayer({ id: "khris-middleton", teamId: "was", leagueId: "nba", firstName: "Khris", lastName: "Middleton", position: "SF", jerseyNumber: 22, heightCm: 201, age: 35, overallRating: 74 }),
  mkPlayer({ id: "bub-carrington", teamId: "was", leagueId: "nba", firstName: "Bub", lastName: "Carrington", position: "PG", jerseyNumber: 7, heightCm: 193, age: 21, overallRating: 74 }),
  mkPlayer({ id: "tre-johnson", teamId: "was", leagueId: "nba", firstName: "Tre", lastName: "Johnson", position: "SG", jerseyNumber: 12, heightCm: 196, age: 19, overallRating: 73 }),
  mkPlayer({ id: "deandre-ayton", teamId: "was", leagueId: "nba", firstName: "Deandre", lastName: "Ayton", position: "C", jerseyNumber: 8, heightCm: 213, age: 28, overallRating: 76 }),
  mkPlayer({ id: "cam-whitmore", teamId: "was", leagueId: "nba", firstName: "Cam", lastName: "Whitmore", position: "SF", jerseyNumber: 1, heightCm: 198, age: 22, overallRating: 74 }),
  mkPlayer({ id: "aj-dybantsa", teamId: "was", leagueId: "nba", firstName: "AJ", lastName: "Dybantsa", position: "SF", jerseyNumber: 4, heightCm: 206, age: 19, overallRating: 74 }),

  // --- Thunder ---
  mkPlayer({ id: "shai-gilgeous-alexander", nationality: "Canada", teamId: "okc", leagueId: "nba", firstName: "Shai", lastName: "Gilgeous-Alexander", position: "PG", jerseyNumber: 2, heightCm: 198, age: 28, overallRating: 98 }),
  mkPlayer({ id: "jalen-williams", teamId: "okc", leagueId: "nba", firstName: "Jalen", lastName: "Williams", position: "SF", jerseyNumber: 8, heightCm: 201, age: 25, overallRating: 89 }),
  mkPlayer({ id: "chet-holmgren", teamId: "okc", leagueId: "nba", firstName: "Chet", lastName: "Holmgren", position: "PF", jerseyNumber: 7, heightCm: 216, age: 24, overallRating: 87 }),
  mkPlayer({ id: "isaiah-hartenstein", nationality: "Allemagne", teamId: "okc", leagueId: "nba", firstName: "Isaiah", lastName: "Hartenstein", position: "PF", jerseyNumber: 55, heightCm: 213, age: 28, overallRating: 79 }),
  mkPlayer({ id: "alex-caruso", teamId: "okc", leagueId: "nba", firstName: "Alex", lastName: "Caruso", position: "SG", jerseyNumber: 9, heightCm: 196, age: 32, overallRating: 76 }),
  mkPlayer({ id: "cason-wallace", teamId: "okc", leagueId: "nba", firstName: "Cason", lastName: "Wallace", position: "SG", jerseyNumber: 22, heightCm: 191, age: 23, overallRating: 76 }),
  mkPlayer({ id: "ajay-mitchell", teamId: "okc", leagueId: "nba", firstName: "Ajay", lastName: "Mitchell", position: "SG", jerseyNumber: 25, heightCm: 193, age: 24, overallRating: 74 }),
  mkPlayer({ id: "jaylin-williams", teamId: "okc", leagueId: "nba", firstName: "Jaylin", lastName: "Williams", position: "SF", jerseyNumber: 6, heightCm: 206, age: 24, overallRating: 72 }),
  mkPlayer({ id: "kenrich-williams", teamId: "okc", leagueId: "nba", firstName: "Kenrich", lastName: "Williams", position: "SG", jerseyNumber: 34, heightCm: 201, age: 31, overallRating: 70 }),
  mkPlayer({ id: "jared-mccain", teamId: "okc", leagueId: "nba", firstName: "Jared", lastName: "McCain", position: "SG", jerseyNumber: 3, heightCm: 190, age: 22, overallRating: 76 }),

  // --- Timberwolves ---
  mkPlayer({ id: "anthony-edwards", teamId: "min", leagueId: "nba", firstName: "Anthony", lastName: "Edwards", position: "SG", jerseyNumber: 5, heightCm: 193, age: 25, overallRating: 94 }),
  mkPlayer({ id: "rudy-gobert", nationality: "France", teamId: "min", leagueId: "nba", firstName: "Rudy", lastName: "Gobert", position: "C", jerseyNumber: 27, heightCm: 213, age: 34, overallRating: 82, injuryRisk: 20 }),
  mkPlayer({ id: "jaden-mcdaniels", teamId: "min", leagueId: "nba", firstName: "Jaden", lastName: "McDaniels", position: "SF", jerseyNumber: 3, heightCm: 203, age: 26, overallRating: 80 }),
  mkPlayer({ id: "lamelo-ball", teamId: "min", leagueId: "nba", firstName: "LaMelo", lastName: "Ball", position: "PG", jerseyNumber: 1, heightCm: 201, age: 25, overallRating: 85 }),
  mkPlayer({ id: "josh-green", nationality: "Australie", teamId: "min", leagueId: "nba", firstName: "Josh", lastName: "Green", position: "SG", jerseyNumber: 10, heightCm: 196, age: 25, overallRating: 74 }),
  mkPlayer({ id: "donte-divincenzo", teamId: "min", leagueId: "nba", firstName: "Donte", lastName: "DiVincenzo", position: "SG", jerseyNumber: 0, heightCm: 193, age: 29, overallRating: 75, injuryRisk: 45 }),
  mkPlayer({ id: "ayo-dosunmu", teamId: "min", leagueId: "nba", firstName: "Ayo", lastName: "Dosunmu", position: "SG", jerseyNumber: 13, heightCm: 193, age: 26, overallRating: 75 }),
  mkPlayer({ id: "terrence-shannon-jr", teamId: "min", leagueId: "nba", firstName: "Terrence", lastName: "Shannon Jr.", position: "SG", jerseyNumber: 4, heightCm: 196, age: 25, overallRating: 73 }),
  mkPlayer({ id: "joan-beringer", nationality: "France", teamId: "min", leagueId: "nba", firstName: "Joan", lastName: "Beringer", position: "C", jerseyNumber: 19, heightCm: 211, age: 19, overallRating: 68 }),
  mkPlayer({ id: "trey-lyles", teamId: "min", leagueId: "nba", firstName: "Trey", lastName: "Lyles", position: "SF", jerseyNumber: 41, heightCm: 208, age: 30, overallRating: 68 }),

  // --- Mavericks ---
  mkPlayer({ id: "cooper-flagg", teamId: "dal", leagueId: "nba", firstName: "Cooper", lastName: "Flagg", position: "SF", jerseyNumber: 32, heightCm: 206, age: 19, overallRating: 84 }),
  mkPlayer({ id: "kyrie-irving", teamId: "dal", leagueId: "nba", firstName: "Kyrie", lastName: "Irving", position: "PG", jerseyNumber: 11, heightCm: 191, age: 34, overallRating: 85, injuryRisk: 70 }),
  mkPlayer({ id: "klay-thompson", teamId: "dal", leagueId: "nba", firstName: "Klay", lastName: "Thompson", position: "SG", jerseyNumber: 31, heightCm: 198, age: 36, overallRating: 75, injuryRisk: 68 }),
  mkPlayer({ id: "pj-washington", teamId: "dal", leagueId: "nba", firstName: "P.J.", lastName: "Washington", position: "PF", jerseyNumber: 25, heightCm: 203, age: 28, overallRating: 78 }),
  mkPlayer({ id: "daniel-gafford", teamId: "dal", leagueId: "nba", firstName: "Daniel", lastName: "Gafford", position: "PF", jerseyNumber: 21, heightCm: 208, age: 27, overallRating: 78 }),
  mkPlayer({ id: "dereck-lively-ii", teamId: "dal", leagueId: "nba", firstName: "Dereck", lastName: "Lively II", position: "C", jerseyNumber: 2, heightCm: 213, age: 22, overallRating: 76, injuryRisk: 55 }),
  mkPlayer({ id: "naji-marshall", teamId: "dal", leagueId: "nba", firstName: "Naji", lastName: "Marshall", position: "SF", jerseyNumber: 3, heightCm: 198, age: 28, overallRating: 74 }),
  mkPlayer({ id: "caleb-martin", teamId: "dal", leagueId: "nba", firstName: "Caleb", lastName: "Martin", position: "SF", jerseyNumber: 16, heightCm: 196, age: 30, overallRating: 72 }),
  mkPlayer({ id: "max-christie", teamId: "dal", leagueId: "nba", firstName: "Max", lastName: "Christie", position: "SG", jerseyNumber: 0, heightCm: 196, age: 23, overallRating: 73 }),
  mkPlayer({ id: "zaccharie-risacher", nationality: "France", teamId: "dal", leagueId: "nba", firstName: "Zaccharie", lastName: "Risacher", position: "SF", jerseyNumber: 10, heightCm: 206, age: 21, overallRating: 76 }),

  // --- Clippers ---
  mkPlayer({ id: "brandon-ingram", teamId: "lac", leagueId: "nba", firstName: "Brandon", lastName: "Ingram", position: "SF", jerseyNumber: 14, heightCm: 203, age: 29, overallRating: 82 }),
  mkPlayer({ id: "gradey-dick", teamId: "lac", leagueId: "nba", firstName: "Gradey", lastName: "Dick", position: "SG", jerseyNumber: 1, heightCm: 198, age: 23, overallRating: 75 }),
  mkPlayer({ id: "darius-garland", teamId: "lac", leagueId: "nba", firstName: "Darius", lastName: "Garland", position: "PG", jerseyNumber: 10, heightCm: 185, age: 26, overallRating: 84 }),
  mkPlayer({ id: "bennedict-mathurin", teamId: "lac", leagueId: "nba", firstName: "Bennedict", lastName: "Mathurin", position: "SG", jerseyNumber: 9, heightCm: 196, age: 24, overallRating: 81 }),
  mkPlayer({ id: "brook-lopez", teamId: "lac", leagueId: "nba", firstName: "Brook", lastName: "Lopez", position: "C", jerseyNumber: 11, heightCm: 216, age: 38, overallRating: 74 }),
  mkPlayer({ id: "kris-dunn", teamId: "lac", leagueId: "nba", firstName: "Kris", lastName: "Dunn", position: "PG", jerseyNumber: 8, heightCm: 196, age: 32, overallRating: 73 }),
  mkPlayer({ id: "derrick-jones-jr", teamId: "lac", leagueId: "nba", firstName: "Derrick", lastName: "Jones Jr.", position: "SF", jerseyNumber: 5, heightCm: 201, age: 29, overallRating: 75 }),
  mkPlayer({ id: "rui-hachimura", nationality: "Japon", teamId: "lac", leagueId: "nba", firstName: "Rui", lastName: "Hachimura", position: "SF", jerseyNumber: 28, heightCm: 203, age: 28, overallRating: 76 }),
  mkPlayer({ id: "johni-broome", teamId: "lac", leagueId: "nba", firstName: "Johni", lastName: "Broome", position: "SF", jerseyNumber: 4, heightCm: 208, age: 24, overallRating: 70 }),
  mkPlayer({ id: "isaiah-jackson", teamId: "lac", leagueId: "nba", firstName: "Isaiah", lastName: "Jackson", position: "SF", jerseyNumber: 23, heightCm: 203, age: 24, overallRating: 71 }),

  // --- Suns ---
  mkPlayer({ id: "devin-booker", teamId: "phx", leagueId: "nba", firstName: "Devin", lastName: "Booker", position: "SG", jerseyNumber: 1, heightCm: 196, age: 29, overallRating: 91 }),
  mkPlayer({ id: "jalen-green", teamId: "phx", leagueId: "nba", firstName: "Jalen", lastName: "Green", position: "SG", jerseyNumber: 4, heightCm: 196, age: 24, overallRating: 80 }),
  mkPlayer({ id: "miles-bridges", teamId: "phx", leagueId: "nba", firstName: "Miles", lastName: "Bridges", position: "SF", jerseyNumber: 22, heightCm: 198, age: 28, overallRating: 79 }),
  mkPlayer({ id: "dillon-brooks", nationality: "Canada", teamId: "phx", leagueId: "nba", firstName: "Dillon", lastName: "Brooks", position: "SG", jerseyNumber: 3, heightCm: 198, age: 30, overallRating: 76 }),
  mkPlayer({ id: "mark-williams", teamId: "phx", leagueId: "nba", firstName: "Mark", lastName: "Williams", position: "C", jerseyNumber: 25, heightCm: 213, age: 24, overallRating: 77 }),
  mkPlayer({ id: "luke-kennard", teamId: "phx", leagueId: "nba", firstName: "Luke", lastName: "Kennard", position: "SG", jerseyNumber: 8, heightCm: 198, age: 30, overallRating: 73 }),
  mkPlayer({ id: "khaman-maluach", nationality: "Soudan du Sud", teamId: "phx", leagueId: "nba", firstName: "Khaman", lastName: "Maluach", position: "C", jerseyNumber: 10, heightCm: 216, age: 19, overallRating: 71 }),
  mkPlayer({ id: "oso-ighodaro", teamId: "phx", leagueId: "nba", firstName: "Oso", lastName: "Ighodaro", position: "PF", jerseyNumber: 11, heightCm: 211, age: 23, overallRating: 70 }),
  mkPlayer({ id: "ryan-dunn", teamId: "phx", leagueId: "nba", firstName: "Ryan", lastName: "Dunn", position: "SF", jerseyNumber: 0, heightCm: 201, age: 22, overallRating: 72 }),
  mkPlayer({ id: "collin-gillespie", teamId: "phx", leagueId: "nba", firstName: "Collin", lastName: "Gillespie", position: "PG", jerseyNumber: 12, heightCm: 185, age: 26, overallRating: 70 }),

  // --- Kings ---
  mkPlayer({ id: "domantas-sabonis", nationality: "Lituanie", teamId: "sac", leagueId: "nba", firstName: "Domantas", lastName: "Sabonis", position: "C", jerseyNumber: 11, heightCm: 211, age: 30, overallRating: 86, injuryRisk: 25 }),
  mkPlayer({ id: "zach-lavine", teamId: "sac", leagueId: "nba", firstName: "Zach", lastName: "LaVine", position: "SG", jerseyNumber: 8, heightCm: 196, age: 31, overallRating: 79, injuryRisk: 40 }),
  mkPlayer({ id: "malik-monk", teamId: "sac", leagueId: "nba", firstName: "Malik", lastName: "Monk", position: "SG", jerseyNumber: 0, heightCm: 191, age: 28, overallRating: 78 }),
  mkPlayer({ id: "keegan-murray", teamId: "sac", leagueId: "nba", firstName: "Keegan", lastName: "Murray", position: "SF", jerseyNumber: 13, heightCm: 203, age: 26, overallRating: 78, injuryRisk: 30 }),
  mkPlayer({ id: "de-andre-hunter", teamId: "sac", leagueId: "nba", firstName: "De'Andre", lastName: "Hunter", position: "SF", jerseyNumber: 15, heightCm: 201, age: 28, overallRating: 78 }),
  mkPlayer({ id: "precious-achiuwa", nationality: "Nigeria", teamId: "sac", leagueId: "nba", firstName: "Precious", lastName: "Achiuwa", position: "SF", jerseyNumber: 9, heightCm: 203, age: 27, overallRating: 72 }),
  mkPlayer({ id: "alex-karaban", teamId: "sac", leagueId: "nba", firstName: "Alex", lastName: "Karaban", position: "SF", jerseyNumber: 33, heightCm: 203, age: 23, overallRating: 70 }),
  mkPlayer({ id: "nique-clifford", teamId: "sac", leagueId: "nba", firstName: "Nique", lastName: "Clifford", position: "SG", jerseyNumber: 0, heightCm: 196, age: 24, overallRating: 68 }),
  mkPlayer({ id: "maxime-raynaud", nationality: "France", teamId: "sac", leagueId: "nba", firstName: "Maxime", lastName: "Raynaud", position: "C", jerseyNumber: 42, heightCm: 216, age: 23, overallRating: 68 }),
  mkPlayer({ id: "darius-acuff-jr", teamId: "sac", leagueId: "nba", firstName: "Darius", lastName: "Acuff Jr.", position: "PG", jerseyNumber: 5, heightCm: 188, age: 19, overallRating: 68 }),

  // --- Grizzlies ---
  mkPlayer({ id: "jaren-jackson-jr", teamId: "mem", leagueId: "nba", firstName: "Jaren", lastName: "Jackson Jr.", position: "PF", jerseyNumber: 13, heightCm: 208, age: 27, overallRating: 86 }),
  mkPlayer({ id: "zach-edey", nationality: "Canada", teamId: "mem", leagueId: "nba", firstName: "Zach", lastName: "Edey", position: "C", jerseyNumber: 14, heightCm: 224, age: 24, overallRating: 78 }),
  mkPlayer({ id: "ty-jerome", teamId: "mem", leagueId: "nba", firstName: "Ty", lastName: "Jerome", position: "SG", jerseyNumber: 2, heightCm: 196, age: 29, overallRating: 76 }),
  mkPlayer({ id: "jaylen-wells", teamId: "mem", leagueId: "nba", firstName: "Jaylen", lastName: "Wells", position: "SF", jerseyNumber: 0, heightCm: 201, age: 22, overallRating: 74 }),
  mkPlayer({ id: "gg-jackson-ii", teamId: "mem", leagueId: "nba", firstName: "GG", lastName: "Jackson II", position: "SF", jerseyNumber: 45, heightCm: 208, age: 21, overallRating: 74 }),
  mkPlayer({ id: "scotty-pippen-jr", teamId: "mem", leagueId: "nba", firstName: "Scotty", lastName: "Pippen Jr.", position: "PG", jerseyNumber: 1, heightCm: 188, age: 26, overallRating: 73 }),
  mkPlayer({ id: "dangelo-russell", teamId: "mem", leagueId: "nba", firstName: "D'Angelo", lastName: "Russell", position: "SG", jerseyNumber: 0, heightCm: 191, age: 30, overallRating: 75 }),
  mkPlayer({ id: "isaiah-stewart", teamId: "mem", leagueId: "nba", firstName: "Isaiah", lastName: "Stewart", position: "PF", jerseyNumber: 28, heightCm: 206, age: 25, overallRating: 74 }),
  mkPlayer({ id: "cameron-boozer", teamId: "mem", leagueId: "nba", firstName: "Cameron", lastName: "Boozer", position: "SF", jerseyNumber: 27, heightCm: 208, age: 19, overallRating: 73 }),
  mkPlayer({ id: "cedric-coward", teamId: "mem", leagueId: "nba", firstName: "Cedric", lastName: "Coward", position: "SG", jerseyNumber: 23, heightCm: 198, age: 23, overallRating: 71 }),

  // --- Pelicans ---
  mkPlayer({ id: "zion-williamson", teamId: "nop", leagueId: "nba", firstName: "Zion", lastName: "Williamson", position: "PF", jerseyNumber: 1, heightCm: 198, age: 26, overallRating: 84, injuryRisk: 88 }),
  mkPlayer({ id: "trey-murphy-iii", teamId: "nop", leagueId: "nba", firstName: "Trey", lastName: "Murphy III", position: "SF", jerseyNumber: 25, heightCm: 203, age: 26, overallRating: 80 }),
  mkPlayer({ id: "dejounte-murray", teamId: "nop", leagueId: "nba", firstName: "Dejounte", lastName: "Murray", position: "SG", jerseyNumber: 5, heightCm: 196, age: 29, overallRating: 79, injuryRisk: 55 }),
  mkPlayer({ id: "herbert-jones", teamId: "nop", leagueId: "nba", firstName: "Herbert", lastName: "Jones", position: "SF", jerseyNumber: 2, heightCm: 201, age: 27, overallRating: 75 }),
  mkPlayer({ id: "yves-missi", nationality: "Cameroun", teamId: "nop", leagueId: "nba", firstName: "Yves", lastName: "Missi", position: "C", jerseyNumber: 21, heightCm: 211, age: 22, overallRating: 74 }),
  mkPlayer({ id: "derik-queen", teamId: "nop", leagueId: "nba", firstName: "Derik", lastName: "Queen", position: "C", jerseyNumber: 22, heightCm: 208, age: 21, overallRating: 75 }),
  mkPlayer({ id: "jordan-poole", teamId: "nop", leagueId: "nba", firstName: "Jordan", lastName: "Poole", position: "SG", jerseyNumber: 3, heightCm: 193, age: 27, overallRating: 75 }),
  mkPlayer({ id: "saddiq-bey", teamId: "nop", leagueId: "nba", firstName: "Saddiq", lastName: "Bey", position: "SG", jerseyNumber: 41, heightCm: 201, age: 27, overallRating: 71 }),
  mkPlayer({ id: "jeremiah-fears", teamId: "nop", leagueId: "nba", firstName: "Jeremiah", lastName: "Fears", position: "PG", jerseyNumber: 0, heightCm: 193, age: 19, overallRating: 70 }),
  mkPlayer({ id: "jordan-hawkins", teamId: "nop", leagueId: "nba", firstName: "Jordan", lastName: "Hawkins", position: "SG", jerseyNumber: 24, heightCm: 196, age: 24, overallRating: 71 }),

  // --- Rockets ---
  mkPlayer({ id: "kevin-durant", teamId: "hou", leagueId: "nba", firstName: "Kevin", lastName: "Durant", position: "PF", jerseyNumber: 7, heightCm: 208, age: 37, overallRating: 90, injuryRisk: 60 }),
  mkPlayer({ id: "alperen-sengun", nationality: "Turquie", teamId: "hou", leagueId: "nba", firstName: "Alperen", lastName: "Şengün", position: "PF", jerseyNumber: 28, heightCm: 211, age: 24, overallRating: 87 }),
  mkPlayer({ id: "amen-thompson", teamId: "hou", leagueId: "nba", firstName: "Amen", lastName: "Thompson", position: "SG", jerseyNumber: 1, heightCm: 201, age: 23, overallRating: 82 }),
  mkPlayer({ id: "fred-vanvleet", teamId: "hou", leagueId: "nba", firstName: "Fred", lastName: "VanVleet", position: "SG", jerseyNumber: 5, heightCm: 183, age: 32, overallRating: 77, injuryRisk: 50 }),
  mkPlayer({ id: "steven-adams", nationality: "Nouvelle-Zélande", teamId: "hou", leagueId: "nba", firstName: "Steven", lastName: "Adams", position: "C", jerseyNumber: 12, heightCm: 211, age: 33, overallRating: 72, injuryRisk: 55 }),
  mkPlayer({ id: "jabari-smith-jr", teamId: "hou", leagueId: "nba", firstName: "Jabari", lastName: "Smith Jr.", position: "PF", jerseyNumber: 10, heightCm: 211, age: 23, overallRating: 77 }),
  mkPlayer({ id: "reed-sheppard", teamId: "hou", leagueId: "nba", firstName: "Reed", lastName: "Sheppard", position: "PG", jerseyNumber: 15, heightCm: 188, age: 22, overallRating: 75 }),
  mkPlayer({ id: "tari-eason", teamId: "hou", leagueId: "nba", firstName: "Tari", lastName: "Eason", position: "SF", jerseyNumber: 17, heightCm: 203, age: 25, overallRating: 76 }),
  mkPlayer({ id: "bogdan-bogdanovic", nationality: "Serbie", teamId: "hou", leagueId: "nba", firstName: "Bogdan", lastName: "Bogdanović", position: "SG", jerseyNumber: 31, heightCm: 196, age: 34, overallRating: 74 }),
  mkPlayer({ id: "clint-capela", nationality: "Suisse", teamId: "hou", leagueId: "nba", firstName: "Clint", lastName: "Capela", position: "C", jerseyNumber: 30, heightCm: 208, age: 32, overallRating: 73 }),

  // --- Spurs ---
  mkPlayer({ id: "victor-wembanyama", nationality: "France", teamId: "sas", leagueId: "nba", firstName: "Victor", lastName: "Wembanyama", position: "C", jerseyNumber: 1, heightCm: 224, age: 22, overallRating: 97 }),
  mkPlayer({ id: "de-aaron-fox", teamId: "sas", leagueId: "nba", firstName: "De'Aaron", lastName: "Fox", position: "PG", jerseyNumber: 4, heightCm: 191, age: 28, overallRating: 87 }),
  mkPlayer({ id: "stephon-castle", teamId: "sas", leagueId: "nba", firstName: "Stephon", lastName: "Castle", position: "SG", jerseyNumber: 5, heightCm: 198, age: 21, overallRating: 80 }),
  mkPlayer({ id: "devin-vassell", teamId: "sas", leagueId: "nba", firstName: "Devin", lastName: "Vassell", position: "SG", jerseyNumber: 24, heightCm: 198, age: 26, overallRating: 79 }),
  mkPlayer({ id: "harrison-barnes", teamId: "sas", leagueId: "nba", firstName: "Harrison", lastName: "Barnes", position: "SF", jerseyNumber: 40, heightCm: 201, age: 34, overallRating: 73 }),
  mkPlayer({ id: "luke-kornet", teamId: "sas", leagueId: "nba", firstName: "Luke", lastName: "Kornet", position: "PF", jerseyNumber: 7, heightCm: 216, age: 31, overallRating: 71 }),
  mkPlayer({ id: "julian-champagnie", teamId: "sas", leagueId: "nba", firstName: "Julian", lastName: "Champagnie", position: "SF", jerseyNumber: 30, heightCm: 201, age: 24, overallRating: 73 }),
  mkPlayer({ id: "keldon-johnson", teamId: "sas", leagueId: "nba", firstName: "Keldon", lastName: "Johnson", position: "SG", jerseyNumber: 3, heightCm: 198, age: 27, overallRating: 73 }),
  mkPlayer({ id: "dylan-harper", teamId: "sas", leagueId: "nba", firstName: "Dylan", lastName: "Harper", position: "SG", jerseyNumber: 2, heightCm: 196, age: 20, overallRating: 74 }),
  mkPlayer({ id: "carter-bryant", teamId: "sas", leagueId: "nba", firstName: "Carter", lastName: "Bryant", position: "SF", jerseyNumber: 11, heightCm: 198, age: 20, overallRating: 69 }),

  // --- Trail Blazers ---
  mkPlayer({ id: "deni-avdija", nationality: "Israël", teamId: "por", leagueId: "nba", firstName: "Deni", lastName: "Avdija", position: "SF", jerseyNumber: 8, heightCm: 206, age: 25, overallRating: 84 }),
  mkPlayer({ id: "ja-morant", teamId: "por", leagueId: "nba", firstName: "Ja", lastName: "Morant", position: "PG", jerseyNumber: 1, heightCm: 191, age: 27, overallRating: 87, injuryRisk: 55 }),
  mkPlayer({ id: "damian-lillard", teamId: "por", leagueId: "nba", firstName: "Damian", lastName: "Lillard", position: "PG", jerseyNumber: 0, heightCm: 188, age: 36, overallRating: 82, injuryRisk: 65 }),
  mkPlayer({ id: "jrue-holiday", teamId: "por", leagueId: "nba", firstName: "Jrue", lastName: "Holiday", position: "SG", jerseyNumber: 5, heightCm: 193, age: 36, overallRating: 78 }),
  mkPlayer({ id: "shaedon-sharpe", nationality: "Canada", teamId: "por", leagueId: "nba", firstName: "Shaedon", lastName: "Sharpe", position: "SG", jerseyNumber: 17, heightCm: 196, age: 23, overallRating: 79 }),
  mkPlayer({ id: "donovan-clingan", teamId: "por", leagueId: "nba", firstName: "Donovan", lastName: "Clingan", position: "C", jerseyNumber: 23, heightCm: 218, age: 22, overallRating: 78 }),
  mkPlayer({ id: "toumani-camara", nationality: "Belgique", teamId: "por", leagueId: "nba", firstName: "Toumani", lastName: "Camara", position: "PF", jerseyNumber: 33, heightCm: 201, age: 25, overallRating: 76 }),
  mkPlayer({ id: "scoot-henderson", teamId: "por", leagueId: "nba", firstName: "Scoot", lastName: "Henderson", position: "PG", jerseyNumber: 0, heightCm: 190, age: 22, overallRating: 74 }),
  mkPlayer({ id: "robert-williams-iii", teamId: "por", leagueId: "nba", firstName: "Robert", lastName: "Williams III", position: "C", jerseyNumber: 35, heightCm: 206, age: 29, overallRating: 70 }),
  mkPlayer({ id: "jeremy-sochan", nationality: "Pologne", teamId: "por", leagueId: "nba", firstName: "Jeremy", lastName: "Sochan", position: "SF", jerseyNumber: 4, heightCm: 206, age: 23, overallRating: 75 }),

  // --- Jazz ---
  mkPlayer({ id: "lauri-markkanen", nationality: "Finlande", teamId: "uta", leagueId: "nba", firstName: "Lauri", lastName: "Markkanen", position: "PF", jerseyNumber: 23, heightCm: 216, age: 29, overallRating: 84 }),
  mkPlayer({ id: "mo-bamba", teamId: "uta", leagueId: "nba", firstName: "Mo", lastName: "Bamba", position: "C", jerseyNumber: 15, heightCm: 213, age: 28, overallRating: 68 }),
  mkPlayer({ id: "keyonte-george", teamId: "uta", leagueId: "nba", firstName: "Keyonte", lastName: "George", position: "PG", jerseyNumber: 3, heightCm: 191, age: 23, overallRating: 77 }),
  mkPlayer({ id: "ace-bailey", teamId: "uta", leagueId: "nba", firstName: "Ace", lastName: "Bailey", position: "SF", jerseyNumber: 5, heightCm: 206, age: 20, overallRating: 76 }),
  mkPlayer({ id: "isaiah-collier", teamId: "uta", leagueId: "nba", firstName: "Isaiah", lastName: "Collier", position: "PG", jerseyNumber: 1, heightCm: 191, age: 21, overallRating: 74 }),
  mkPlayer({ id: "kyle-filipowski", teamId: "uta", leagueId: "nba", firstName: "Kyle", lastName: "Filipowski", position: "PF", jerseyNumber: 22, heightCm: 211, age: 22, overallRating: 75 }),
  mkPlayer({ id: "svi-mykhailiuk", nationality: "Ukraine", teamId: "uta", leagueId: "nba", firstName: "Svi", lastName: "Mykhailiuk", position: "SF", jerseyNumber: 19, heightCm: 201, age: 29, overallRating: 68 }),
  mkPlayer({ id: "jaxson-hayes", teamId: "uta", leagueId: "nba", firstName: "Jaxson", lastName: "Hayes", position: "PF", jerseyNumber: 11, heightCm: 213, age: 26, overallRating: 71 }),
  mkPlayer({ id: "jusuf-nurkic", nationality: "Bosnie-Herzégovine", teamId: "uta", leagueId: "nba", firstName: "Jusuf", lastName: "Nurkić", position: "C", jerseyNumber: 27, heightCm: 211, age: 31, overallRating: 71 }),
  mkPlayer({ id: "darryn-peterson", teamId: "uta", leagueId: "nba", firstName: "Darryn", lastName: "Peterson", position: "SG", jerseyNumber: 8, heightCm: 198, age: 19, overallRating: 72 }),
];
