import type { Team } from "@/lib/types";

export const teams: Team[] = [
  // --- NBA ---
  {
    id: "lal",
    leagueId: "nba",
    conferenceId: "nba-west",
    city: "Los Angeles",
    name: "Lakers",
    abbreviation: "LAL",
    marketAppeal: 95,
    primaryColor: "#552583",
    secondaryColor: "#FDB927",
  },
  {
    id: "bos",
    leagueId: "nba",
    conferenceId: "nba-east",
    city: "Boston",
    name: "Celtics",
    abbreviation: "BOS",
    marketAppeal: 78,
    primaryColor: "#007A33",
    secondaryColor: "#BA9653",
  },
  {
    id: "gsw",
    leagueId: "nba",
    conferenceId: "nba-west",
    city: "Golden State",
    name: "Warriors",
    abbreviation: "GSW",
    marketAppeal: 90,
    primaryColor: "#1D428A",
    secondaryColor: "#FFC72C",
  },
  {
    id: "mil",
    leagueId: "nba",
    conferenceId: "nba-east",
    city: "Milwaukee",
    name: "Bucks",
    abbreviation: "MIL",
    marketAppeal: 35,
    primaryColor: "#00471B",
    secondaryColor: "#EEE1C6",
  },
  {
    id: "den",
    leagueId: "nba",
    conferenceId: "nba-west",
    city: "Denver",
    name: "Nuggets",
    abbreviation: "DEN",
    marketAppeal: 68,
    primaryColor: "#0E2240",
    secondaryColor: "#FEC524",
  },
  {
    id: "nyk",
    leagueId: "nba",
    conferenceId: "nba-east",
    city: "New York",
    name: "Knicks",
    abbreviation: "NYK",
    marketAppeal: 93,
    primaryColor: "#006BB6",
    secondaryColor: "#F58426",
  },
  {
    id: "mia",
    leagueId: "nba",
    conferenceId: "nba-east",
    city: "Miami",
    name: "Heat",
    abbreviation: "MIA",
    marketAppeal: 92,
    primaryColor: "#98002E",
    secondaryColor: "#F9A01B",
  },
  {
    id: "phi",
    leagueId: "nba",
    conferenceId: "nba-east",
    city: "Philadelphia",
    name: "76ers",
    abbreviation: "PHI",
    marketAppeal: 65,
    primaryColor: "#006BB6",
    secondaryColor: "#ED174C",
  },
  {
    id: "cle",
    leagueId: "nba",
    conferenceId: "nba-east",
    city: "Cleveland",
    name: "Cavaliers",
    abbreviation: "CLE",
    marketAppeal: 38,
    primaryColor: "#6F263D",
    secondaryColor: "#FFB81C",
  },
  {
    id: "orl",
    leagueId: "nba",
    conferenceId: "nba-east",
    city: "Orlando",
    name: "Magic",
    abbreviation: "ORL",
    marketAppeal: 62,
    primaryColor: "#0077C0",
    secondaryColor: "#C4CED4",
  },
  {
    id: "ind",
    leagueId: "nba",
    conferenceId: "nba-east",
    city: "Indiana",
    name: "Pacers",
    abbreviation: "IND",
    marketAppeal: 40,
    primaryColor: "#002D62",
    secondaryColor: "#FDBB30",
  },
  {
    id: "atl",
    leagueId: "nba",
    conferenceId: "nba-east",
    city: "Atlanta",
    name: "Hawks",
    abbreviation: "ATL",
    marketAppeal: 70,
    primaryColor: "#E03A3E",
    secondaryColor: "#C1D32F",
  },
  {
    id: "chi",
    leagueId: "nba",
    conferenceId: "nba-east",
    city: "Chicago",
    name: "Bulls",
    abbreviation: "CHI",
    marketAppeal: 72,
    primaryColor: "#CE1141",
    secondaryColor: "#000000",
  },
  {
    id: "bkn",
    leagueId: "nba",
    conferenceId: "nba-east",
    city: "Brooklyn",
    name: "Nets",
    abbreviation: "BKN",
    marketAppeal: 88,
    primaryColor: "#000000",
    secondaryColor: "#777D84",
  },
  {
    id: "tor",
    leagueId: "nba",
    conferenceId: "nba-east",
    city: "Toronto",
    name: "Raptors",
    abbreviation: "TOR",
    marketAppeal: 68,
    primaryColor: "#CE1141",
    secondaryColor: "#000000",
  },
  {
    id: "det",
    leagueId: "nba",
    conferenceId: "nba-east",
    city: "Detroit",
    name: "Pistons",
    abbreviation: "DET",
    marketAppeal: 40,
    primaryColor: "#C8102E",
    secondaryColor: "#1D42BA",
  },
  {
    id: "cha",
    leagueId: "nba",
    conferenceId: "nba-east",
    city: "Charlotte",
    name: "Hornets",
    abbreviation: "CHA",
    marketAppeal: 45,
    primaryColor: "#1D1160",
    secondaryColor: "#00788C",
  },
  {
    id: "was",
    leagueId: "nba",
    conferenceId: "nba-east",
    city: "Washington",
    name: "Wizards",
    abbreviation: "WAS",
    marketAppeal: 60,
    primaryColor: "#002B5C",
    secondaryColor: "#E31837",
  },
  {
    id: "okc",
    leagueId: "nba",
    conferenceId: "nba-west",
    city: "Oklahoma City",
    name: "Thunder",
    abbreviation: "OKC",
    marketAppeal: 30,
    primaryColor: "#007AC1",
    secondaryColor: "#EF3B24",
  },
  {
    id: "min",
    leagueId: "nba",
    conferenceId: "nba-west",
    city: "Minnesota",
    name: "Timberwolves",
    abbreviation: "MIN",
    marketAppeal: 48,
    primaryColor: "#0C2340",
    secondaryColor: "#236192",
  },
  {
    id: "dal",
    leagueId: "nba",
    conferenceId: "nba-west",
    city: "Dallas",
    name: "Mavericks",
    abbreviation: "DAL",
    marketAppeal: 72,
    primaryColor: "#00538C",
    secondaryColor: "#002B5E",
  },
  {
    id: "lac",
    leagueId: "nba",
    conferenceId: "nba-west",
    city: "LA",
    name: "Clippers",
    abbreviation: "LAC",
    marketAppeal: 93,
    primaryColor: "#C8102E",
    secondaryColor: "#1D428A",
  },
  {
    id: "phx",
    leagueId: "nba",
    conferenceId: "nba-west",
    city: "Phoenix",
    name: "Suns",
    abbreviation: "PHX",
    marketAppeal: 65,
    primaryColor: "#1D1160",
    secondaryColor: "#E56020",
  },
  {
    id: "sac",
    leagueId: "nba",
    conferenceId: "nba-west",
    city: "Sacramento",
    name: "Kings",
    abbreviation: "SAC",
    marketAppeal: 42,
    primaryColor: "#5A2D81",
    secondaryColor: "#63727A",
  },
  {
    id: "mem",
    leagueId: "nba",
    conferenceId: "nba-west",
    city: "Memphis",
    name: "Grizzlies",
    abbreviation: "MEM",
    marketAppeal: 33,
    primaryColor: "#5D76A9",
    secondaryColor: "#12173F",
  },
  {
    id: "nop",
    leagueId: "nba",
    conferenceId: "nba-west",
    city: "New Orleans",
    name: "Pelicans",
    abbreviation: "NOP",
    marketAppeal: 58,
    primaryColor: "#0C2340",
    secondaryColor: "#C8102E",
  },
  {
    id: "hou",
    leagueId: "nba",
    conferenceId: "nba-west",
    city: "Houston",
    name: "Rockets",
    abbreviation: "HOU",
    marketAppeal: 68,
    primaryColor: "#CE1141",
    secondaryColor: "#000000",
  },
  {
    id: "sas",
    leagueId: "nba",
    conferenceId: "nba-west",
    city: "San Antonio",
    name: "Spurs",
    abbreviation: "SAS",
    marketAppeal: 50,
    primaryColor: "#C4CED4",
    secondaryColor: "#000000",
  },
  {
    id: "por",
    leagueId: "nba",
    conferenceId: "nba-west",
    city: "Portland",
    name: "Trail Blazers",
    abbreviation: "POR",
    marketAppeal: 55,
    primaryColor: "#E03A3E",
    secondaryColor: "#000000",
  },
  {
    id: "uta",
    leagueId: "nba",
    conferenceId: "nba-west",
    city: "Utah",
    name: "Jazz",
    abbreviation: "UTA",
    marketAppeal: 38,
    primaryColor: "#002B5C",
    secondaryColor: "#F9A01B",
  },

  // --- WNBA ---
  {
    id: "las-vegas-aces",
    leagueId: "wnba",
    conferenceId: "wnba-west",
    city: "Las Vegas",
    name: "Aces",
    abbreviation: "LVA",
    marketAppeal: 88,
    primaryColor: "#000000",
    secondaryColor: "#C8102E",
  },
  {
    id: "new-york-liberty",
    leagueId: "wnba",
    conferenceId: "wnba-east",
    city: "New York",
    name: "Liberty",
    abbreviation: "NYL",
    marketAppeal: 90,
    primaryColor: "#86CEBC",
    secondaryColor: "#000000",
  },
  {
    id: "seattle-storm",
    leagueId: "wnba",
    conferenceId: "wnba-west",
    city: "Seattle",
    name: "Storm",
    abbreviation: "SEA",
    marketAppeal: 65,
    primaryColor: "#2C5234",
    secondaryColor: "#FE5000",
  },
  {
    id: "connecticut-sun",
    leagueId: "wnba",
    conferenceId: "wnba-east",
    city: "Connecticut",
    name: "Sun",
    abbreviation: "CON",
    marketAppeal: 35,
    primaryColor: "#E03A3E",
    secondaryColor: "#0A2240",
  },
  {
    id: "minnesota-lynx",
    leagueId: "wnba",
    conferenceId: "wnba-west",
    city: "Minnesota",
    name: "Lynx",
    abbreviation: "MIN",
    marketAppeal: 50,
    primaryColor: "#236192",
    secondaryColor: "#9EA2A2",
  },
  {
    id: "indiana-fever",
    leagueId: "wnba",
    conferenceId: "wnba-east",
    city: "Indiana",
    name: "Fever",
    abbreviation: "IND",
    marketAppeal: 45,
    primaryColor: "#002D62",
    secondaryColor: "#E03A3E",
  },
  {
    id: "atlanta-dream",
    leagueId: "wnba",
    conferenceId: "wnba-east",
    city: "Atlanta",
    name: "Dream",
    abbreviation: "ATL",
    marketAppeal: 62,
    primaryColor: "#E31837",
    secondaryColor: "#5091CD",
  },
  {
    id: "chicago-sky",
    leagueId: "wnba",
    conferenceId: "wnba-east",
    city: "Chicago",
    name: "Sky",
    abbreviation: "CHI",
    marketAppeal: 70,
    primaryColor: "#418FDE",
    secondaryColor: "#FFCD00",
  },
  {
    id: "washington-mystics",
    leagueId: "wnba",
    conferenceId: "wnba-east",
    city: "Washington",
    name: "Mystics",
    abbreviation: "WAS",
    marketAppeal: 58,
    primaryColor: "#002B5C",
    secondaryColor: "#E03A3E",
  },
  {
    id: "dallas-wings",
    leagueId: "wnba",
    conferenceId: "wnba-west",
    city: "Dallas",
    name: "Wings",
    abbreviation: "DAL",
    marketAppeal: 65,
    primaryColor: "#C4D600",
    secondaryColor: "#002B5C",
  },
  {
    id: "los-angeles-sparks",
    leagueId: "wnba",
    conferenceId: "wnba-west",
    city: "Los Angeles",
    name: "Sparks",
    abbreviation: "LAS",
    marketAppeal: 90,
    primaryColor: "#552583",
    secondaryColor: "#FFC72C",
  },
  {
    id: "phoenix-mercury",
    leagueId: "wnba",
    conferenceId: "wnba-west",
    city: "Phoenix",
    name: "Mercury",
    abbreviation: "PHX",
    marketAppeal: 62,
    primaryColor: "#201747",
    secondaryColor: "#E56020",
  },
  {
    id: "golden-state-valkyries",
    leagueId: "wnba",
    conferenceId: "wnba-west",
    city: "Golden State",
    name: "Valkyries",
    abbreviation: "GSV",
    marketAppeal: 85,
    primaryColor: "#240B3B",
    secondaryColor: "#BFB4C8",
  },
];
