import type { Team } from "@/lib/types";

export const teams: Team[] = [
  // --- NBA ---
  {
    id: "lal",
    leagueId: "nba",
    conferenceId: "nba-west",
    city: "Los Angeles",
    name: "Lakers",
    abbreviation: "LAL",
    primaryColor: "#552583",
    secondaryColor: "#FDB927",
  },
  {
    id: "bos",
    leagueId: "nba",
    conferenceId: "nba-east",
    city: "Boston",
    name: "Celtics",
    abbreviation: "BOS",
    primaryColor: "#007A33",
    secondaryColor: "#BA9653",
  },
  {
    id: "gsw",
    leagueId: "nba",
    conferenceId: "nba-west",
    city: "Golden State",
    name: "Warriors",
    abbreviation: "GSW",
    primaryColor: "#1D428A",
    secondaryColor: "#FFC72C",
  },
  {
    id: "mil",
    leagueId: "nba",
    conferenceId: "nba-east",
    city: "Milwaukee",
    name: "Bucks",
    abbreviation: "MIL",
    primaryColor: "#00471B",
    secondaryColor: "#EEE1C6",
  },
  {
    id: "den",
    leagueId: "nba",
    conferenceId: "nba-west",
    city: "Denver",
    name: "Nuggets",
    abbreviation: "DEN",
    primaryColor: "#0E2240",
    secondaryColor: "#FEC524",
  },
  {
    id: "nyk",
    leagueId: "nba",
    conferenceId: "nba-east",
    city: "New York",
    name: "Knicks",
    abbreviation: "NYK",
    primaryColor: "#006BB6",
    secondaryColor: "#F58426",
  },

  // --- WNBA ---
  {
    id: "las-vegas-aces",
    leagueId: "wnba",
    conferenceId: "wnba-west",
    city: "Las Vegas",
    name: "Aces",
    abbreviation: "LVA",
    primaryColor: "#000000",
    secondaryColor: "#C8102E",
  },
  {
    id: "new-york-liberty",
    leagueId: "wnba",
    conferenceId: "wnba-east",
    city: "New York",
    name: "Liberty",
    abbreviation: "NYL",
    primaryColor: "#86CEBC",
    secondaryColor: "#000000",
  },
  {
    id: "seattle-storm",
    leagueId: "wnba",
    conferenceId: "wnba-west",
    city: "Seattle",
    name: "Storm",
    abbreviation: "SEA",
    primaryColor: "#2C5234",
    secondaryColor: "#FE5000",
  },
  {
    id: "connecticut-sun",
    leagueId: "wnba",
    conferenceId: "wnba-east",
    city: "Connecticut",
    name: "Sun",
    abbreviation: "CON",
    primaryColor: "#E03A3E",
    secondaryColor: "#0A2240",
  },
  {
    id: "minnesota-lynx",
    leagueId: "wnba",
    conferenceId: "wnba-west",
    city: "Minnesota",
    name: "Lynx",
    abbreviation: "MIN",
    primaryColor: "#236192",
    secondaryColor: "#9EA2A2",
  },
  {
    id: "indiana-fever",
    leagueId: "wnba",
    conferenceId: "wnba-east",
    city: "Indiana",
    name: "Fever",
    abbreviation: "IND",
    primaryColor: "#002D62",
    secondaryColor: "#E03A3E",
  },
];
